### ISSUE TITLE
oneway=yes influences pedestrian routing but should not

### ISSUE THREAD

**Issue by jengelh** [valhalla/valhalla#4778] opened 2024-06-25 16:16 UTC
[Route query in question](https://valhalla.openstreetmap.de/directions?profile=pedestrian&wps=9.933963418006899%2C51.53355291228649%2C9.933979511260986%2C51.53392665135226)

Observed:
![1](https://github.com/valhalla/valhalla/assets/8861948/0224307a-ea11-4c85-974d-de2ead62c8a1)

Expected:
Direct Route

Valhalla seems to take oneway=yes too literally for pedestrian routing, but it is documented in the OSM wiki as applying to vehicles only.

**Comment by nilsnolde** [comment] 2024-06-25 18:07
Ha, funny, just had the same one in a different context. it's actually a duplicate of https://github.com/valhalla/valhalla/issues/4014.

IMO still a mapping error.

**Closed by nilsnolde** 2024-06-25 18:07 UTC
