### ISSUE TITLE
Going backwards on roads that are close together results in incorrect matching

### ISSUE THREAD

**Issue by Stefan781** [valhalla/valhalla#4208] opened 2023-07-18 08:57 UTC
I have two roads that are very close to each other (around a meter or two away). They merge at the two ends. If the user goes forwards to one of the merging points and then backwards, continuing their route after the second merging point (see the left side of the image), then the map matching returns an incorrect road, implying that the user took the second road back (see the right side of the picture, in red the erroneous matching is visualized). The GPS signal is precise and falls almost exactly on the actual road taken.

![image](https://github.com/valhalla/valhalla/assets/130654984/b2605bd4-273a-456d-8630-3111cc917818)

Is this a known issue? I tried setting the search radius to one meter but it still results in an incorrect matching. Even if it didn't, this workaround would give me incorrect matching for other measurements which are not so precise. The streets are marked as pedestrian areas and the costing is set to _pedestrian_. Is there a way to specify that going backwards should be prioritized by the algorithm? Or some other solution to this issue?

**Comment by M393** [comment] 2023-07-19 12:45
May be a duplicate of #3627

**Comment by kevinkreiser** [comment] 2023-07-19 15:51
we disallow uturns by default (in that we set intermediate `location.type`s to `through`) however you can allow uturns by setting the location type to `break` or `via`. this is not possible if you use the `encoded_polyline` style of input though so you'll have to use the `shape` style of input. see some examples in the api docs: https://github.com/valhalla/valhalla/blob/master/docs/docs/api/map-matching/api-reference.md

**Comment by Stefan781** [comment] 2023-07-20 05:48
I am already using the shape style. Neither "type" : "break" nor "type" : "via" solved the issue. The issue that @M393 linked seems to conclude that (at least in their case) this is a bug. Is that correct?

**Comment by kevinkreiser** [comment] 2023-07-20 10:32
it looks like a regression yes. we have an example over there so let's continue on that issue

**Closed by kevinkreiser** 2023-07-20 10:32 UTC
