### ISSUE TITLE
OSX Test Randomly Fails

### ISSUE THREAD

**Issue by kevinkreiser** [valhalla/valhalla#2911] opened 2021-03-03 15:41 UTC
I believe we've seen this before, but it looks like there is a bug in the double bucket queue unit test which leads to a segfault.

```
[ 77%] Generating routing.log
/bin/bash: line 1: 15120 Segmentation fault: 11  /Users/distiller/project/build/test/routing >&/Users/distiller/project/build/test/routing.log
[FAIL] routing
[==========] Running 4 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 4 tests from Routing
[ RUN      ] Routing.TestAddRemove
[       OK ] Routing.TestAddRemove (7 ms)
[ RUN      ] Routing.TestSimulation
make[3]: *** [test/routing.log] Error 139
make[3]: *** Deleting file `test/routing.log'
make[2]: *** [test/CMakeFiles/run-routing.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
```

**Comment by danpat** [comment] 2021-03-03 17:23
Confirmed - it's easy to reproduce this on current `master` with:

```
$ ./test/routing  --gtest_filter=Routing.TestSimulation --gtest_repeat=1000
...
Repeating all tests (iteration 215) . . .

Note: Google Test filter = Routing.TestSimulation
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from Routing
[ RUN      ] Routing.TestSimulation
Segmentation fault: 11
```

I'll rebuild in debug and post a stack trace.

**Comment by danpat** [comment] 2021-03-03 17:47
```
Repeating all tests (iteration 784) . . .

Note: Google Test filter = Routing.TestSimulation
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from Routing
[ RUN      ] Routing.TestSimulation
Process 39529 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x10)
    frame #0: 0x0000000100014efb routing`(anonymous namespace)::TrySimulation(loop_count=333, expansion_size=60, max_increment_cost=100) at routing.cc:111:26
   108 	      const auto newcost = std::floor(min_cost + 1 + test::rand01(gen) * max_increment_cost);
   109 	      if (i % 2 == 0 && !track.empty()) {
   110 	        // Decrease cost
-> 111 	        const auto idx = *std::next(track.begin(), test::rand01(gen) * track.size());
   112 	        if (newcost < costs[idx].sortcost()) {
   113 	          adjlist.decrease(idx, newcost);
   114 	          costs[idx] = {newcost};
Target 0: (routing) stopped.
```

Once again, looks like an unfortunate use of `rand` in a test....

**Comment by danpat** [comment] 2021-03-03 19:03
Interestingly, this was fixed in the `double_bucket_queue.cc` test back in 53bd9e7a521e13b743e3030ea2dedaf5db161bcc where the random generator was modified to no longer return 1.0.

**Comment by mandeepsandhu** [comment] 2021-03-03 19:48
> Interestingly, this was fixed in the `double_bucket_queue.cc` test back in [53bd9e7](https://github.com/valhalla/valhalla/commit/53bd9e7a521e13b743e3030ea2dedaf5db161bcc) where the random generator was modified to no longer return 1.0.

Yeah its interesting since any thing less than `1.0` _should_ result in the index being less than `size()` (the decimal part is truncated). Maybe we should have an assert there to capture the value returned by `test::rand01(gen)` if index is invalid?

**Comment by danpat** [comment] 2021-03-03 20:13
I added an intermediary variable to make it possible to inspect the random result during the crash (not sure if lldb knows about the temporary value by the time the segfault occurs) - it is indeed 1.0.

That seems like a violation of https://en.cppreference.com/w/cpp/numeric/random/uniform_real_distribution:

> Produces random floating-point values i, uniformly distributed on the interval [a, b)


```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x10)
    frame #0: 0x0000000100014ef8 routing`(anonymous namespace)::TrySimulation(loop_count=333, expansion_size=60, max_increment_cost=100) at routing.cc:112:26
   109 	      if (i % 2 == 0 && !track.empty()) {
   110 	        // Decrease cost
   111 	        const auto r = test::rand01(gen);
-> 112 	        const auto idx = *std::next(track.begin(), r * track.size());
   113 	        if (newcost < costs[idx].sortcost()) {
   114 	          adjlist.decrease(idx, newcost);
   115 	          costs[idx] = {newcost};
Target 0: (routing) stopped.
(lldb) p r
(const float) $0 = 1
```

**Closed** 2021-03-03 20:39 UTC
Labels: bug
