### ISSUE TITLE
sources_to_targets many-to-many error

### ISSUE THREAD

**Issue by khamaileon** [valhalla/valhalla#4325] opened 2023-10-11 11:57 UTC
I'm getting strange results with the sources_to_targets service. I have 2 sources and 10 destinations. When I do the query with 1 of the 2 sources, I get the right results but when I do the query with 2 sources, the times from the 2nd source to the destinations are 0 except for the first 2. Am I missing something?

## 2 sources, 10 targets

```bash
curl http://localhost:8002/sources_to_targets --data '{"costing":"bicycle","sources":[{"lon":2.317459001599275,"lat":48.8751299326598},{"lon":2.3119596463541825,"lat":48.85384434940977}],"targets":[{"lon":2.307796,"lat":48.86623},{"lon":2.307764,"lat":48.866886},{"lon":2.30851,"lat":48.86646},{"lon":2.310229,"lat":48.866295},{"lon":2.30776,"lat":48.86703},{"lon":2.307752,"lat":48.867016},{"lon":2.307711,"lat":48.864807},{"lon":2.31317,"lat":48.86609},{"lon":2.313193,"lat":48.865444},{"lon":2.310083,"lat":48.866734}]}' | jq '.'
```

```json
{
  "algorithm": "timedistancematrix",
  "units": "kilometers",
  "sources": [
    [
      {
        "lon": 2.317459,
        "lat": 48.87513
      },
      {
        "lon": 2.31196,
        "lat": 48.853844
      }
    ]
  ],
  "targets": [
    [
      {
        "lon": 2.307796,
        "lat": 48.86623
      },
      {
        "lon": 2.307764,
        "lat": 48.866886
      },
      {
        "lon": 2.30851,
        "lat": 48.86646
      },
      {
        "lon": 2.310229,
        "lat": 48.866295
      },
      {
        "lon": 2.30776,
        "lat": 48.86703
      },
      {
        "lon": 2.307752,
        "lat": 48.867016
      },
      {
        "lon": 2.307711,
        "lat": 48.864807
      },
      {
        "lon": 2.31317,
        "lat": 48.86609
      },
      {
        "lon": 2.313193,
        "lat": 48.865444
      },
      {
        "lon": 2.310083,
        "lat": 48.866734
      }
    ]
  ],
  "sources_to_targets": [
    [
      {
        "distance": 1.76,
        "time": 431,
        "to_index": 0,
        "from_index": 0
      },
      {
        "distance": 1.695,
        "time": 413,
        "to_index": 1,
        "from_index": 0
      },
      {
        "distance": 1.658,
        "time": 369,
        "to_index": 2,
        "from_index": 0
      },
      {
        "distance": 2.233,
        "time": 511,
        "to_index": 3,
        "from_index": 0
      },
      {
        "distance": 1.671,
        "time": 377,
        "to_index": 4,
        "from_index": 0
      },
      {
        "distance": 1.556,
        "time": 343,
        "to_index": 5,
        "from_index": 0
      },
      {
        "distance": 2.217,
        "time": 507,
        "to_index": 6,
        "from_index": 0
      },
      {
        "distance": 2.219,
        "time": 508,
        "to_index": 7,
        "from_index": 0
      },
      {
        "distance": 1.589,
        "time": 350,
        "to_index": 8,
        "from_index": 0
      },
      {
        "distance": 1.694,
        "time": 351,
        "to_index": 9,
        "from_index": 0
      }
    ],
    [
      {
        "distance": 1.622,
        "time": 337,
        "to_index": 0,
        "from_index": 1
      },
      {
        "distance": 1.612,
        "time": 358,
        "to_index": 1,
        "from_index": 1
      },
      {
        "distance": 0,
        "time": 0,
        "to_index": 2,
        "from_index": 1
      },
      {
        "distance": 0,
        "time": 0,
        "to_index": 3,
        "from_index": 1
      },
      {
        "distance": 0,
        "time": 0,
        "to_index": 4,
        "from_index": 1
      },
      {
        "distance": 0,
        "time": 0,
        "to_index": 5,
        "from_index": 1
      },
      {
        "distance": 0,
        "time": 0,
        "to_index": 6,
        "from_index": 1
      },
      {
        "distance": 0,
        "time": 0,
        "to_index": 7,
        "from_index": 1
      },
      {
        "distance": 0,
        "time": 0,
        "to_index": 8,
        "from_index": 1
      },
      {
        "distance": 0,
        "time": 0,
        "to_index": 9,
        "from_index": 1
      }
    ]
  ]
}
```

## 1 source, 10 targets

```bash
curl http://localhost:8002/sources_to_targets --data '{"costing":"bicycle","sources":[{"lon":2.3119596463541825,"lat":48.85384434940977}],"targets":[{"lon":2.307796,"lat":48.86623},{"lon":2.307764,"lat":48.866886},{"lon":2.30851,"lat":48.86646},{"lon":2.310229,"lat":48.866295},{"lon":2.30776,"lat":48.86703},{"lon":2.307752,"lat":48.867016},{"lon":2.307711,"lat":48.864807},{"lon":2.31317,"lat":48.86609},{"lon":2.313193,"lat":48.865444},{"lon":2.310083,"lat":48.866734}]}' | jq '.'
```

```json
{
  "algorithm": "timedistancematrix",
  "units": "kilometers",
  "sources": [
    [
      {
        "lon": 2.31196,
        "lat": 48.853844
      }
    ]
  ],
  "targets": [
    [
      {
        "lon": 2.307796,
        "lat": 48.86623
      },
      {
        "lon": 2.307764,
        "lat": 48.866886
      },
      {
        "lon": 2.30851,
        "lat": 48.86646
      },
      {
        "lon": 2.310229,
        "lat": 48.866295
      },
      {
        "lon": 2.30776,
        "lat": 48.86703
      },
      {
        "lon": 2.307752,
        "lat": 48.867016
      },
      {
        "lon": 2.307711,
        "lat": 48.864807
      },
      {
        "lon": 2.31317,
        "lat": 48.86609
      },
      {
        "lon": 2.313193,
        "lat": 48.865444
      },
      {
        "lon": 2.310083,
        "lat": 48.866734
      }
    ]
  ],
  "sources_to_targets": [
    [
      {
        "distance": 1.658,
        "time": 369,
        "to_index": 0,
        "from_index": 0
      },
      {
        "distance": 2.233,
        "time": 511,
        "to_index": 1,
        "from_index": 0
      },
      {
        "distance": 1.671,
        "time": 377,
        "to_index": 2,
        "from_index": 0
      },
      {
        "distance": 1.556,
        "time": 343,
        "to_index": 3,
        "from_index": 0
      },
      {
        "distance": 2.217,
        "time": 507,
        "to_index": 4,
        "from_index": 0
      },
      {
        "distance": 2.219,
        "time": 508,
        "to_index": 5,
        "from_index": 0
      },
      {
        "distance": 1.589,
        "time": 350,
        "to_index": 6,
        "from_index": 0
      },
      {
        "distance": 1.694,
        "time": 351,
        "to_index": 7,
        "from_index": 0
      },
      {
        "distance": 1.622,
        "time": 337,
        "to_index": 8,
        "from_index": 0
      },
      {
        "distance": 1.612,
        "time": 358,
        "to_index": 9,
        "from_index": 0
      }
    ]
  ]
}
```

# 1 source, 10 targets

```bash
curl http://localhost:8002/sources_to_targets --data '{"costing":"bicycle","sources":[{"lon":2.317459001599275,"lat":48.8751299326598}],"targets":[{"lon":2.307796,"lat":48.86623},{"lon":2.307764,"lat":48.866886},{"lon":2.30851,"lat":48.86646},{"lon":2.310229,"lat":48.866295},{"lon":2.30776,"lat":48.86703},{"lon":2.307752,"lat":48.867016},{"lon":2.307711,"lat":48.864807},{"lon":2.31317,"lat":48.86609},{"lon":2.313193,"lat":48.865444},{"lon":2.310083,"lat":48.866734}]}' | jq '.'
```

```json
{
  "algorithm": "timedistancematrix",
  "units": "kilometers",
  "sources": [
    [
      {
        "lon": 2.317459,
        "lat": 48.87513
      }
    ]
  ],
  "targets": [
    [
      {
        "lon": 2.307796,
        "lat": 48.86623
      },
      {
        "lon": 2.307764,
        "lat": 48.866886
      },
      {
        "lon": 2.30851,
        "lat": 48.86646
      },
      {
        "lon": 2.310229,
        "lat": 48.866295
      },
      {
        "lon": 2.30776,
        "lat": 48.86703
      },
      {
        "lon": 2.307752,
        "lat": 48.867016
      },
      {
        "lon": 2.307711,
        "lat": 48.864807
      },
      {
        "lon": 2.31317,
        "lat": 48.86609
      },
      {
        "lon": 2.313193,
        "lat": 48.865444
      },
      {
        "lon": 2.310083,
        "lat": 48.866734
      }
    ]
  ],
  "sources_to_targets": [
    [
      {
        "distance": 1.76,
        "time": 431,
        "to_index": 0,
        "from_index": 0
      },
      {
        "distance": 1.695,
        "time": 413,
        "to_index": 1,
        "from_index": 0
      },
      {
        "distance": 1.881,
        "time": 460,
        "to_index": 2,
        "from_index": 0
      },
      {
        "distance": 1.691,
        "time": 408,
        "to_index": 3,
        "from_index": 0
      },
      {
        "distance": 1.679,
        "time": 409,
        "to_index": 4,
        "from_index": 0
      },
      {
        "distance": 1.681,
        "time": 410,
        "to_index": 5,
        "from_index": 0
      },
      {
        "distance": 1.973,
        "time": 463,
        "to_index": 6,
        "from_index": 0
      },
      {
        "distance": 1.414,
        "time": 337,
        "to_index": 7,
        "from_index": 0
      },
      {
        "distance": 1.486,
        "time": 351,
        "to_index": 8,
        "from_index": 0
      },
      {
        "distance": 1.747,
        "time": 426,
        "to_index": 9,
        "from_index": 0
      }
    ]
  ]
}
```

Valhalla 3.4.0 via ghcr.io/gis-ops/docker-valhalla/valhalla:3.4.0

**Comment by nilsnolde** [comment] 2023-10-13 03:39
Hm I can't reproduce that with the FOSSGIS server, which runs Valhalla on a commit from Aug 12 (and data from yesterday or so), quite a bit after 3.4.0, incl a few (maybe) relevant matrix PR's. I've also never observed that behavior myself and can't remember any other related issue, yet it seems like it feels like smth that should pop up all the time if there was such a bug. Also I can't really think of anything that could be wrong on our side (but that's not really a proof :sweat_smile:).

Can you try the `latest` image?

BTW, the FOSSGIS instance returns quite different results from yours. Are you using (unchanged) OSM data or smth else? (not that it's relevant to the problem, just curious)

**Comment by khamaileon** [comment] 2023-10-21 08:20
Hi Nils, I changed to ghcr.io/gis-ops/docker-valhalla/valhalla:latest and it works again. I also have a custom build in production based on 3.4.0 and I have the same problem so we can also exclude docker-valhalla from the equation.

I'm going to use the latest version for now but I think it would be great to pin a 3.4.1 version.

> BTW, the FOSSGIS instance returns quite different results from yours. Are you using (unchanged) OSM data or smth else? (not that it's relevant to the problem, just curious)

Just the original Geofabrik file. Do you think I should regenerate the graph with the latest version of Valhalla?

**Comment by nilsnolde** [comment] 2023-10-21 12:28
Yeah we should probably release soon again. There’s lots of PRs in the pipeline though, we probably wait for at least a few of them to be merged. 

You shouldn’t need to do new tiles, your problems are related with algorithms only.

**Closed by nilsnolde** 2023-10-21 12:28 UTC
