### ISSUE TITLE
valhalla.json is wiped out when multiple instances access

### ISSUE THREAD

**Issue by brad-4k** [valhalla/valhalla#3753] opened 2022-09-20 16:42 UTC
Thank you for all the hard work, I can't say it enough.

I don't know if this belongs in "issues" but we have multiple Valhalla instances accessing the same valhalla.json file and at some point the valhalla.json ends up with a size of zero.  What might be causing this and what are your thoughts on mitigating this?

Thank you!

**Comment by nilsnolde** [comment] 2022-09-20 17:26
It's always worth mentioning what setup you're using and the commands you performed when the issue is occurring. Valhalla itself is not doing anything with the config json in write-y mode.

So I guess you're using our gis-ops image (that's the only setup I'm aware of that out-of-the-box alters the json)? Our image does some alterations to the json with `jq` and I'm not sure what exactly happens if multiple instances perform the `jq` command in the entrypoint script at the same time, but likely you're seeing the effect of that. So, one solution would be to have the instances start slightly offset in time, like 10 secs should be plenty, or to provide each instance with its own config json.

**Comment by kevinkreiser** [comment] 2022-09-21 22:54
lets close this and open an issue over in the gis ops repos if you need more help on that particular configuration

**Closed by kevinkreiser** 2022-09-21 22:54 UTC

**Comment by brad-4k** [comment] 2022-09-26 16:50
@nilsnolde understood, thank you again for your detailed replies.  My initial solution was to make the file read only.  We'll see how that goes for a while :)

@kevinkreiser thank you.  I'll bring it up over there (gis ops)
