### ISSUE TITLE
Building a container image for ARM64 architecture

### ISSUE THREAD

**Issue by samvanemelen** [valhalla/valhalla#3424] opened 2021-11-22 16:06 UTC
For a project I will need to process thousands of valhalla API requests in a few seconds. A single computer would take minutes to complete this, but I am looking into building a cluster of Raspberry Pi 4's running kubernetes to host the valhalla docker image. This way I should end up with a +- scalable server to run valhalla routing algorithms quickly. But it seems as if Valhalla is currently not compatibly with the PI's ARM64 architecture by default. How feasible is it, if possible at all, for me to build a docker image for the ARM64 architecture? Or are there other ways to achieve what it is that I need?

**Comment by TimMcCauley** [comment] 2021-11-22 16:28
Did you have a look at this discussion @samvanemelen  https://github.com/valhalla/valhalla/discussions/2887 ?

**Comment by kevinkreiser** [comment] 2021-11-22 18:30
Why is it not compatible? I haven't done it for a while but it used to build on the pi

**Comment by samvanemelen** [comment] 2021-11-23 10:18
Thanks for the responses! @kevinkreiser, I have been working with the docker images for Valhalla, they are currently only built for 'linux/amd64' if I'm correct. That's why I was facing issues with the PI's.

I had not found that discussion @TimMcCauley, thanks for sharing it with me. What I take away from this, is that building the code from source on ARM64 should work, potentially by disabling some features as in #2887. And according to @kevinkreiser disabling features should not even necessary.

Correct me if I'm wrong, but to get a working container I can deploy on the RPI4, I should rebuild the app from source, and create a container from that built?

Also, I realize this topic might have been better suited for the 'Discussion' section. My apologies for that and I will take it into account in the future.

**Comment by nilsnolde** [comment] 2021-11-24 07:08
You should be able to crossbuild for arm64 on any architecture with docker buildx. Have a look at other images that offer other architectures and specifically their CI setup. The main challenge will probably be to get all dependencies installed. If you get a recipe you could consider sharing it so we can include it in our image builds, either here or over at https://github.com/gis-ops/docker-valhalla

**Comment by kelindi** [comment] 2022-01-10 21:44
@samvanemelen How did you end up creating a container for the RPI4?

**Comment by samvanemelen** [comment] 2022-01-11 07:34
@kelindi I am not there yet. I am first trying to simply build it on the RPI4, but I keep struggling with certain dependencies (prime-server). I will keep this issue updated when anything changes.

**Comment by twen** [comment] 2022-01-11 08:36
I recently switched to a new Mac with M1 Processor and I'm also having trouble building and running Valhalla. On my old system I was running it in Docker and I'm currently working an a docker image for ARM.
My (work in progress and chaotic) Dockerfile looks as follows:


```FROM ubuntu:latest

ARG DEBIAN_FRONTEND=noninteractive
WORKDIR /install-tmp
RUN apt-get update && \
    apt-get install -y python git libsqlite3-dev libspatialite-dev liblua5.1-0-dev libluajit-5.1-dev libgeos-dev \
        libgeos++-dev spatialite-bin wget curl parallel cmake make libtool pkg-config g++ gcc curl unzip jq lcov \
        protobuf-compiler vim-common locales libboost-all-dev libcurl4-openssl-dev zlib1g-dev liblz4-dev \
        libprotobuf-dev libgeos-dev libgeos++-dev libluajit-5.1-dev libspatialite-dev libsqlite3-dev wget sqlite3 \
        spatialite-bin python-all-dev libcurl4-openssl-dev libzmq3-dev libczmq-dev patch

RUN git clone https://github.com/kevinkreiser/prime_server.git
WORKDIR /install-tmp/prime_server
RUN git checkout 0.7.0
RUN git submodule update --init --recursive
RUN ./autogen.sh
RUN ./configure
RUN make -j$(nproc)
RUN make install

WORKDIR /install-tmp

RUN bash -c 'source /etc/lsb-release && if [[ $(python -c "print(int($DISTRIB_RELEASE > 15))") > 0 ]]; then apt-get install -y libsqlite3-mod-spatialite; fi'
RUN git clone --recurse-submodules https://github.com/valhalla/valhalla.git
WORKDIR /install-tmp/valhalla
RUN git checkout 3.1.4
WORKDIR /install-tmp/valhalla/build
RUN cmake .. -DCMAKE_BUILD_TYPE=Release
RUN make -j$(nproc)
RUN make install

WORKDIR /install-tmp

ADD config/map-match.lua /install-tmp/valhalla/lua/
ADD config/valhalla.json /install-tmp/

CMD valhalla_service valhalla.json 1
```

The error output during the image build is

```
[ 41%] Built target valhalla-baldr
[ 41%] Compiling lua/admin.lua to admin_lua_proc.h
[ 41%] Compiling lua/graph.lua to graph_lua_proc.h
[ 41%] Building CXX object src/odin/CMakeFiles/valhalla-odin.dir/enhancedtrippath.cc.o
Scanning dependencies of target valhalla-mjolnir
[ 45%] Building CXX object src/mjolnir/CMakeFiles/valhalla-mjolnir.dir/adminbuilder.cc.o
[ 48%] Building CXX object src/odin/CMakeFiles/valhalla-odin.dir/maneuver.cc.o
In file included from /install-tmp/valhalla/valhalla/baldr/graphid.h:11,
                 from /install-tmp/valhalla/valhalla/mjolnir/util.h:13,
                 from /install-tmp/valhalla/src/mjolnir/adminbuilder.cc:11:
/install-tmp/valhalla/valhalla/baldr/json.h: In member function 'std::ostream& valhalla::baldr::json::OstreamVisitor::operator()(const string&) const':
/install-tmp/valhalla/valhalla/baldr/json.h:113:17: error: comparison is always true due to limited range of data type [-Werror=type-limits]
  113 |           if (c >= 0 && c < 32) {
      |               ~~^~~~
[ 48%] Building CXX object src/odin/CMakeFiles/valhalla-odin.dir/sign.cc.o
[ 48%] Building CXX object src/odin/CMakeFiles/valhalla-odin.dir/signs.cc.o
[ 48%] Building CXX object src/odin/CMakeFiles/valhalla-odin.dir/util.cc.o
[ 48%] Building CXX object src/odin/CMakeFiles/valhalla-odin.dir/transitrouteinfo.cc.o
[ 48%] Building CXX object src/odin/CMakeFiles/valhalla-odin.dir/worker.cc.o
cc1plus: all warnings being treated as errors
make[2]: *** [src/mjolnir/CMakeFiles/valhalla-mjolnir.dir/build.make:71: src/mjolnir/CMakeFiles/valhalla-mjolnir.dir/adminbuilder.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2218: src/mjolnir/CMakeFiles/valhalla-mjolnir.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 48%] Built target valhalla-odin
make: *** [Makefile:152: all] Error 2
1 error occurred:
        * Status: The command '/bin/sh -c make -j$(nproc)' returned a non-zero code: 2, Code: 2
```

Maybe it helps @samvanemelen and maybe someone has some input on how to solve the issue.

**Comment by nilsnolde** [comment] 2022-01-11 09:08
you should have a look at all the options in the root CMakeLists.txt: https://github.com/valhalla/valhalla/blob/af4272baf8d981b71df605b75a0aa7857c129d87/CMakeLists.txt#L21-L38.

Specifically you wanna turn off `ENABLE_SINGLE_FILES_WERROR` which might get you a step further in the build (or complete it).

**Comment by twen** [comment] 2022-01-11 23:14
Thanks for the hint with the CMakeLists.txt.
I changed the setting `ENABLE_SINGLE_FILES_WERROR` and was able to complete the build.
As far as I can tell, building the admin.sqlite file (valhalla_build_admins) seems to work but building tiles doesn't.

```
root@a29936eb6534:~# valhalla_build_tiles -c /data/valhalla/valhalla.json /pbf/processed/switzerland-latest.osm.pbf 
2022/01/11 23:08:24.574950 [INFO] Start stage = initialize End stage = cleanup
2022/01/11 23:08:24.576047 [INFO] Using LUA script: /install-tmp/valhalla/lua/map-match.lua
2022/01/11 23:08:24.579534 [INFO] Parsing files for ways: /pbf/processed/switzerland-latest.osm.pbf
2022/01/11 23:08:24.580894 [INFO] Parsing ways...
Segmentation fault (core dumped)
```

I will try later with already build tiles to see if the service itself will work.

**Comment by ImreSamu** [comment] 2022-01-11 23:37
@twen :

> As far as I can tell, building the admin.sqlite file (valhalla_build_admins) seems to work but building tiles doesn't.

You can add a `make tests` ; `make check` to your build: 
* see osx ci/cd steps:  https://github.com/valhalla/valhalla/blob/master/.circleci/config.yml#L147-L152

**Comment by twen** [comment] 2022-01-12 11:25
Although it is not relevant here, `make test` in primeserver passed.

`make check` in Valhalla did not pass, error output is as follows:

```
[FAIL] isochrone
[==========] Running 3 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 3 tests from Isochrones
[ RUN      ] Isochrones.Basic
/install-tmp/valhalla/test/isochrone.cc:96: Failure
Expected equality of these values:
  actual_geom.Size()
    Which is: 5
  expected_geom.Size()
    Which is: 350
/install-tmp/valhalla/test/isochrone.cc:96: Failure
Expected equality of these values:
  actual_geom.Size()
    Which is: 5
  expected_geom.Size()
    Which is: 273
/install-tmp/valhalla/test/isochrone.cc:96: Failure
Expected equality of these values:
  actual_geom.Size()
    Which is: 4
  expected_geom.Size()
    Which is: 273
[  FAILED  ] Isochrones.Basic (90 ms)
[ RUN      ] Isochrones.OriginEdge
[          ] generating map PBF at test/data/isochrones/origin_edge/map.pbf
[          ] building tiles in test/data/isochrones/origin_edge
[          ] isochrone with mjolnir.tile_dir = test/data/isochrones/origin_edge with locations b with costing pedestrian
[          ] Valhalla request is: {"locations":[{"lon":0.03593248178978409,"lat":0.0,"type":"break"}],"costing":"pedestrian","costing_options":{"pedestrian":{"speed_types":["freeflow","constrained","predicted"]}},"verbose":true,"contours":[{"time":"10"}],"shape_match":"map_snap"}
{"features":[{"properties":{"fill":"#bf4040","fillOpacity":0.33,"fill-opacity":0.33,"fillColor":"#bf4040","color":"#bf4040","contour":10,"opacity":0.33,"metric":"time"},"geometry":{"coordinates":[[0.039785,-0.000853],[0.042586,-0.000654],[0.043886,0.000000],[0.042586,0.000654],[0.039785,0.000853]],"type":"LineString"},"type":"Feature"}],"type":"FeatureCollection"}
/install-tmp/valhalla/test/isochrone.cc:189: Failure
Expected equality of these values:
  within(WaypointToBoostPoint("b"), polygon)
    Which is: false
  true
[  FAILED  ] Isochrones.OriginEdge (186 ms)
[ RUN      ] Isochrones.LongEdge
[          ] generating map PBF at test/data/isochrones/long_edge/map.pbf
[          ] building tiles in test/data/isochrones/long_edge
[          ] isochrone with mjolnir.tile_dir = test/data/isochrones/long_edge with locations a with costing pedestrian
[          ] Valhalla request is: {"locations":[{"lon":0.0,"lat":-0.0017966240891925997,"type":"break"}],"costing":"pedestrian","costing_options":{"pedestrian":{"speed_types":["freeflow","constrained","predicted"]}},"verbose":true,"contours":[{"time":"15"}],"shape_match":"map_snap"}
{"features":[{"properties":{"fill":"#bf4040","fillOpacity":0.33,"fill-opacity":0.33,"fillColor":"#bf4040","color":"#bf4040","contour":15,"opacity":0.33,"metric":"time"},"geometry":{"coordinates":[[0.001158,0.000045],[0.001048,-0.000844],[-0.000875,-0.000922],[-0.000875,-0.002672],[0.008183,-0.002614]],"type":"LineString"},"type":"Feature"}],"type":"FeatureCollection"}
[  FAILED  ] Isochrones.Basic (90 ms)
[ RUN      ] Isochrones.OriginEdge
[          ] generating map PBF at test/data/isochrones/origin_edge/map.pbf
[          ] building tiles in test/data/isochrones/origin_edge
[          ] isochrone with mjolnir.tile_dir = test/data/isochrones/origin_edge with locations b with costing pedestrian
[          ] Valhalla request is: {"locations":[{"lon":0.03593248178978409,"lat":0.0,"type":"break"}],"costing":"pedestrian","costing_options":{"pedestrian":{"speed_types":["freeflow","constrained","predicted"]}},"verbose":true,"contours":[{"time":"10"}],"shape_match":"map_snap"}
{"features":[{"properties":{"fill":"#bf4040","fillOpacity":0.33,"fill-opacity":0.33,"fillColor":"#bf4040","color":"#bf4040","contour":10,"opacity":0.33,"metric":"time"},"geometry":{"coordinates":[[0.039785,-0.000853],[0.042586,-0.000654],[0.043886,0.000000],[0.042586,0.000654],[0.039785,0.000853]],"type":"LineString"},"type":"Feature"}],"type":"FeatureCollection"}
/install-tmp/valhalla/test/isochrone.cc:189: Failure
Expected equality of these values:
  within(WaypointToBoostPoint("b"), polygon)
    Which is: false
  true
[  FAILED  ] Isochrones.OriginEdge (186 ms)
[ RUN      ] Isochrones.LongEdge
[          ] generating map PBF at test/data/isochrones/long_edge/map.pbf
[          ] building tiles in test/data/isochrones/long_edge
[          ] isochrone with mjolnir.tile_dir = test/data/isochrones/long_edge with locations a with costing pedestrian
[          ] Valhalla request is: {"locations":[{"lon":0.0,"lat":-0.0017966240891925997,"type":"break"}],"costing":"pedestrian","costing_options":{"pedestrian":{"speed_types":["freeflow","constrained","predicted"]}},"verbose":true,"contours":[{"time":"15"}],"shape_match":"map_snap"}
{"features":[{"properties":{"fill":"#bf4040","fillOpacity":0.33,"fill-opacity":0.33,"fillColor":"#bf4040","color":"#bf4040","contour":15,"opacity":0.33,"metric":"time"},"geometry":{"coordinates":[[0.001158,0.000045],[0.001048,-0.000844],[-0.000875,-0.000922],[-0.000875,-0.002672],[0.008183,-0.002614]],"type":"LineString"},"type":"Feature"}],"type":"FeatureCollection"}
[       OK ] Isochrones.LongEdge (178 ms)
[----------] 3 tests from Isochrones (473 ms total)

[----------] Global test environment tear-down
[==========] 3 tests from 1 test suite ran. (473 ms total)
[  PASSED  ] 1 test.
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] Isochrones.Basic
[  FAILED  ] Isochrones.OriginEdge

 2 FAILED TESTS
make[3]: *** [test/CMakeFiles/run-isochrone.dir/build.make:61: test/isochrone.log] Error 1
make[3]: *** Deleting file 'test/isochrone.log'
make[2]: *** [CMakeFiles/Makefile2:5139: test/CMakeFiles/run-isochrone.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:4323: test/CMakeFiles/check.dir/rule] Error 2
make: *** [Makefile:1486: check] Error 2
```

I'm currently a little bit short on time, sorry for that. I hope I can add more details later.

**Comment by zkwurst** [comment] 2022-10-09 19:37
@twen were you able to make any progress here? My dockerized arm64 build fails on the same isochrone checks. 

If I skip the checks, everything builds and the isochrone service runs but the return geometry isn't right: only disconnected line segments or small polygons. Haven't made any progress on why or fix yet.

![image](https://user-images.githubusercontent.com/22687793/194775983-22341877-eec4-4bcd-9c55-23c2aeb3201e.png)

**Comment by nilsnolde** [comment] 2022-10-09 20:20
Ha.. Why's it swallowing 30% of the segments.. IIRC the contouring algo is pretty basic (in terms of used libs, it's actually pretty complex/awful to look at haha). Would love to debug into it, but don't have any ARM64 stuff lying around..

**Comment by twen** [comment] 2022-10-10 10:06
@zkwurst I haven't spent more time on Valhalla on ARM. I was able to compile it. I had no luck building the Valhalla tiles on ARM, so I just build them on an Intel machine.
As far as I can tell, routing seems to work on ARM with the tiles I've build on Intel. But I haven't testet other features like matching, ...
A quick test with the isochrone API revealed that it doesn't work on my ARM machine with the tiles I build on Intel.

**Comment by cfoehrdes** [comment] 2023-09-04 11:13
Is it not runnable at all on M1/M2 Mac? Trying to run as amd64 image trough the emulation for development but getting segfault directly after starting. Running with defaults and Germany Geofabrik PBF.

```
2023-09-04 13:10:02 ============================
2023-09-04 13:10:02 = Build the initial graph. =
2023-09-04 13:10:02 ============================
2023-09-04 13:10:02 2023/09/04 11:10:02.964726 [INFO] Running valhalla_build_tiles with 2 thread(s).
2023-09-04 13:10:02 2023/09/04 11:10:02.966571 [INFO] Start stage = initialize End stage = build
2023-09-04 13:10:02 /valhalla/scripts/configure_valhalla.sh: line 210:    61 Segmentation fault      valhalla_build_tiles -c ${CONFIG_FILE} -e build ${files}
```

**Comment by cfoehrdes** [comment] 2023-09-04 11:14
Is it not runnable at all on M1/M2 Mac? Trying to run as amd64 image trough the emulation for development but getting segfault directly after starting. Running with defaults and Germany Geofabrik PBF.

```
2023-09-04 13:10:02 ============================
2023-09-04 13:10:02 = Build the initial graph. =
2023-09-04 13:10:02 ============================
2023-09-04 13:10:02 2023/09/04 11:10:02.964726 [INFO] Running valhalla_build_tiles with 2 thread(s).
2023-09-04 13:10:02 2023/09/04 11:10:02.966571 [INFO] Start stage = initialize End stage = build
2023-09-04 13:10:02 /valhalla/scripts/configure_valhalla.sh: line 210:    61 Segmentation fault      valhalla_build_tiles -c ${CONFIG_FILE} -e build ${files}
```

**Comment by amjith** [comment] 2023-09-06 04:07
I am also encountering a segmentation fault when I try to use the amd64 emulation in a Mac M1. 

```
$ docker run -t --platform=linux/amd64 --name valhalla_gis-ops -p 8002:8002 -v $PWD/map_files:/custom_files ghcr.io/gis-ops/docker-valhalla/valhalla:3.3.0


INFO: Running container with user valhalla UID 59999 and GID 59999.

WARNING: Hash not found for: /custom_files/utah-latest.osm.pbf!
WARNING: No routing tiles found at /custom_files/valhalla_tiles.tar or /custom_files/valhalla_tiles, starting new build..
INFO: Running build tiles with: /custom_files/valhalla.json /custom_files/utah-latest.osm.pbf

============================
= Build the initial graph. =
============================
2023/09/06 04:06:25.00875 [INFO] Start stage = initialize End stage = build
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
/valhalla/scripts/configure_valhalla.sh: line 172:   113 Segmentation fault      valhalla_build_tiles -c ${CONFIG_FILE} -e build ${files}
```

**Comment by ianthetechie** [comment] 2023-09-06 07:24
I can confirm that I ran into a variety of issues on the M1 as well. (If there's a meta-issue or a project, let me know; we can move discussion there.) None of this is specific to building a container, but...

* I also get segfaults when running the x86 docker image. I have not tried building tiles; I have a separate (Linux) server that does tile builds.
* Building on the M1 is a bit difficult but doable.
* There may be some lingering undefined behaviors or arch- or OS-specific quirks that it relies on, since `make check` fails. See #4048. This does not appear to be M1-specific, but it is slightly easier to hit on the M1.

**Comment by nilsnolde** [comment] 2023-09-06 10:20
Yeah, a meta issue would make sense, to consolidate the issues we're seeing and maybe even have a workaround. We'd appreciate someone else doing that.

Most people are complaining about our image though: https://github.com/gis-ops/docker-valhalla. I forgot but shouldn't the following work:
- build the valhalla/valhalla (base image) on and for arm64
- then build the gis-ops/valhalla image on that base image on and for arm64

Can someone on M1/2 report if this at least builds & runs, incl building tiles? In any case, there'll still be issues with isochrones output, see https://github.com/valhalla/valhalla/issues/4108. But routing shouldn't have any issues.

**Comment by amjith** [comment] 2023-09-10 02:47
I have an M1. I built the valhalla/valhalla image and used that as the base for gis-ops/valhalla image. It starts the server successfully in 8002 and serves the `/traceroute` endpoint with pre-computed tiles. 

But it is NOT able to build tiles on startup. It crashes with a segmentation fault. 

```
2023/09/10 02:45:38.558851 [INFO] Running valhalla_build_tiles with 5 thread(s).
2023/09/10 02:45:38.558891 [INFO] Start stage = initialize End stage = build
2023/09/10 02:45:38.563189 [INFO] Parsing files for ways: /custom_files/norcal-latest.osm.pbf
2023/09/10 02:45:38.568499 [INFO] Parsing ways...
/valhalla/scripts/configure_valhalla.sh: line 210:    42 Segmentation fault      valhalla_build_tiles -c ${CONFIG_FILE} -e build ${files}
```

**Comment by zkwurst** [comment] 2023-09-10 16:54
@nilsnolde I can build and run a custom Valhalla docker image on my M1 mac. It builds tiles and serves isochrones. I've added the files I'm using below. Solving the segmentation fault building tiles and the weird chunking of isochrones were the most persistent issues.

**Fair warning:** The files are super bloated with all the intertwined workarounds I've tried. I got it working and haven't gone back to refactor or test which parts are necessary. Some of the code is flat-out unneeded or specific to my own project dependencies but the files are working and should work generically as-is. If folks have time to take another pass at them they should be a good starting point for a working m1 aarch64 build. 


### docker compose
```yaml
valhalla:
    build: 
      context: ./valhalla
      dockerfile: valhalla.dockerfile
    ports:
      - 8002:8002
```

### valhalla.dockerfile
```Dockerfile
FROM ubuntu@sha256:9ff03c2930fce7e915f3b321c6c601380ffb845140bd36715c44ec31d7ae551e as builder

ARG DEBIAN_FRONTEND=noninteractive
ARG DEB_BUILD_MAINT_OPTIONS=optimize=+lto

ARG CONCURRENCY
ARG BUILDPLATFORM

ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8

# set paths
ENV PATH /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$PATH
ENV LD_LIBRARY_PATH /usr/local/aarch64-linux-gnu:/usr/lib/aarch64-linux-gnu:/usr/local/lib:/lib/aarch64-linux-gnu:/usr/local/lib:/lib/aarch64-linux-gnu:$LD_LIBRARY_PATH

WORKDIR /usr/local/src
COPY ./install-linux-deps.sh /usr/local/src/install-linux-deps.sh
RUN bash /usr/local/src/install-linux-deps.sh
RUN rm -rf /usr/local/src/install-linux-deps.sh

# Get Noto Emoji Regular font, despite it being deprecated by Google
RUN wget https://github.com/googlefonts/noto-emoji/blob/9a5261d871451f9b5183c93483cbd68ed916b1e9/fonts/NotoEmoji-Regular.ttf?raw=true --content-disposition -P /usr/share/fonts/
# For some reason this one is missing in the default packages
RUN wget https://github.com/stamen/terrain-classic/blob/master/fonts/unifont-Medium.ttf?raw=true --content-disposition -P /usr/share/fonts/

# clone valhalla repo and submodules
ARG VALHALLA_BRANCH=3.4.0
RUN git clone --branch $VALHALLA_BRANCH https://github.com/valhalla/valhalla.git

WORKDIR /usr/local/src/valhalla/valhalla
RUN ls -la \
    && git submodule sync \
    && git submodule update --init --recursive
RUN rm -rf build && mkdir build


RUN python3 -m pip install --upgrade "conan<2.0.0" requests

# configure the build with symbols turned on so that crashes can be triaged
WORKDIR /usr/local/src/valhalla/build

# cmake as debug build
RUN CXXFLAGS=-DGEOS_INLINE cmake .. \
  -DCMAKE_BUILD_TYPE=Debug \
  -DCMAKE_C_COMPILER=/usr/bin/aarch64-linux-gnu-gcc \
  -DCMAKE_THREAD_LIBS_INIT="-lpthread" \
  -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64"

### make
RUN VERBOSE=1 make all -j${CONCURRENCY:-$(nproc)} LIBS=-lpthread
RUN VERBOSE=1 make LIBS=-lpthread install

# we wont leave the source around but we'll drop the commit hash we'll also keep the locales
WORKDIR /usr/local/src
RUN cd valhalla && echo "https://github.com/valhalla/valhalla/tree/$(git rev-parse HEAD)" > ../valhalla_version
RUN for f in valhalla/locales/*.json; do cat ${f} | python3 -c 'import sys; import json; print(json.load(sys.stdin)["posix_locale"])'; done > valhalla_locales
RUN rm -rf valhalla

# the binaries are huge with all the symbols so we strip them but keep the debug there if we need it
WORKDIR /usr/local/bin
RUN for f in valhalla_*; do objcopy --only-keep-debug $f $f.debug; done
RUN tar -cvf valhalla.debug.tar valhalla_*.debug && gzip -9 valhalla.debug.tar
RUN rm -f valhalla_*.debug
RUN strip --strip-debug --strip-unneeded valhalla_* || true
RUN strip /usr/local/lib/libvalhalla.a
RUN strip /usr/lib/python3/dist-packages/valhalla/python_valhalla*.so


####################################################################
FROM ubuntu@sha256:9ff03c2930fce7e915f3b321c6c601380ffb845140bd36715c44ec31d7ae551e as runner

# copy the important stuff from the build stage to the runner image
COPY --from=builder /usr/local /usr/local
COPY --from=builder /usr/lib/python3/dist-packages/valhalla/* /usr/lib/python3/dist-packages/valhalla/

RUN export DEBIAN_FRONTEND=noninteractive && apt update && \
    apt install -y \
      build-essential \
      crossbuild-essential-arm64 \
      gcc-aarch64-linux-gnu \
      binutils-aarch64-linux-gnu \
      dateutils \
      fonts-hanazono \
      fonts-noto-cjk \
      fonts-noto-hinted \
      fonts-noto-unhinted \
      fonts-unifont \
      gnupg2 \
      gdal-bin \
      wget \
      rsyslog

### for arch64 compilation
RUN export DEBIAN_FRONTEND=noninteractive && apt update && \
    apt install -y \
      libasan6 \
      libcurl4 \
      libczmq4 \
      libluajit-5.1-dev \
      libprotobuf-dev \
      libubsan1 \
      libsqlite3-dev \
      libsqlite3-mod-spatialite \
      libzmq5 \
      zlib1g \
      curl \
      gdb-multiarch \
      locales \
      parallel \
      protobuf-compiler \
      python3 \
      python3-distutils \
      python-is-python3 \
      spatialite-bin \
      unzip \
    && apt-get update && apt-get -y upgrade \
    && locale-gen $LANG && update-locale LANG=$LANG \
    && cat /usr/local/src/valhalla_locales | xargs -d '\n' -n1 locale-gen && \
    rm -rf /var/lib/apt/lists/* && \
    \
    # python smoke test
    python3 -c "import valhalla,sys; print(sys.version, valhalla)"


COPY ./setup.sh /setup.sh
RUN chmod +x /setup.sh
CMD ["/bin/bash", "/setup.sh"]

```

### install-linux-deps.sh
```sh
#!/usr/bin/env bash
# Script for shared dependencies

set -x -o errexit -o pipefail -o nounset

export DEB_BUILD_MAINT_OPTIONS=optimize=+lto

apt-get update --assume-yes
env DEBIAN_FRONTEND=noninteractive apt-get install --yes --quiet \
    build-essential \
    crossbuild-essential-arm64 \
    gcc-aarch64-linux-gnu \
    binutils-aarch64-linux-gnu \
    gnupg2 \
    linux-libc-dev \
    libpthread-stubs0-dev \
    sqlite3 \
    lz4 \
    fonts-hanazono \
    fonts-noto-cjk \
    fonts-noto-hinted \
    fonts-noto-unhinted \
    fonts-unifont \
    libosmium2-dev \
    libboost-program-options-dev \
    libbz2-dev \
    wget

# Now, go through and install the build dependencies
apt-get update --assume-yes
env DEBIAN_FRONTEND=noninteractive apt-get install --yes --quiet \
    autoconf \
    automake \
    ccache \
    clang \
    clang-tidy \
    coreutils \
    curl \
    cmake \
    g++ \
    gcc \
    git \
    jq \
    lcov \
    libasan6 \
    libboost-all-dev \
    libc6-dev \
    libcurl4-openssl-dev \
    libczmq-dev \
    libgeos++-dev \
    libgeos-dev \
    libjsoncpp-dev \
    libluajit-5.1-dev \
    liblz4-dev \
    libprotobuf-dev \
    libspatialite-dev \
    libsqlite3-dev \
    libsqlite3-mod-spatialite \
    libssl-dev \
    libtool \
    libubsan1 \
    libzmq3-dev \
    lld \
    locales \
    make \
    osmium-tool \
    parallel \
    pkg-config \
    protobuf-compiler \
    python3-all-dev \
    python3-shapely \
    python3-pip \
    spatialite-bin \
    unzip \
    zlib1g-dev \
  && apt-get update && apt-get -y upgrade \
  && locale-gen $LANG && update-locale LANG=$LANG \
  && apt-get update && apt-get -y upgrade \
  && rm -rf /var/lib/apt/lists/*
  
# build prime_server from source
readonly primeserver_dir=/usr/local/src/prime_server
git clone --recurse-submodules https://github.com/kevinkreiser/prime_server $primeserver_dir
pushd $primeserver_dir
./autogen.sh && ./configure LDFLAGS='-pthread' && \
make -j${CONCURRENCY:-$(nproc)} LIBS=-lpthread install && \
popd && \
rm -r $primeserver_dir

# for boost
python3 -m pip install --upgrade "conan<2.0.0" requests shapely
```

### setup.sh
```sh
#!/usr/bin/env bash
set -o nounset
set -o errexit
set -o pipefail

set -e

### create required directories in shared volume
SHARED_VOLUME=vol_valhalla

echo "creating directories..."

mkdir -p $SHARED_VOLUME && cd $SHARED_VOLUME
mkdir -p valhalla_tiles
mkdir -p conf

# echo "downloading OSM data..."
### smaller OSM file for azerbaijan ~32MB  
# OSM_FILE_URL="https://download.geofabrik.de/europe/switzerland-latest.osm.pbf"
# OSM_FILE_URL="https://download.geofabrik.de/asia/azerbaijan-latest.osm.pbf"
OSM_FILE_URL="https://download.geofabrik.de/north-america/us/california/norcal-latest.osm.pbf"
# OSM_FILE_URL="https://download.geofabrik.de/europe/germany/bayern/oberbayern-latest.osm.pbf"
OSM_FILE_NEW="osm_latest.osm.pbf"

# download data
wget --no-verbose \
    --show-progress \
    --progress=bar:force:noscroll \
    "$OSM_FILE_URL" \
    -O "$OSM_FILE_NEW"

echo "creating config..."
valhalla_build_config \
    --mjolnir-tile-dir ${PWD}/valhalla_tiles \
    --mjolnir-tile-extract ${PWD}/valhalla_tiles.tar \
    --mjolnir-traffic-extract ${PWD}/valhalla_traffic.tar \
    --mjolnir-timezone ${PWD}/valhalla_tiles/timezones.sqlite \
    --mjolnir-admin ${PWD}/valhalla_tiles/admins.sqlite \
    > ${PWD}/conf/valhalla.json


echo "building timezones..."
valhalla_build_timezones > ${PWD}/valhalla_tiles/timezones.sqlite

echo "building admin areas..."
valhalla_build_admins --config ${PWD}/conf/valhalla.json "$OSM_FILE_NEW"

echo "building tiles..."
valhalla_build_tiles -c ${PWD}/conf/valhalla.json "$OSM_FILE_NEW"

echo "building tile index..."
valhalla_build_extract -c ${PWD}/conf/valhalla.json -v

echo "starting server..."
# run on n number of cores
valhalla_service ${PWD}/conf/valhalla.json 4

# # if needed, keep container running for debugging
# while true; do sleep 1; done;
```

**Comment by nilsnolde** [comment] 2023-09-10 17:03
Thanks for the input @zkwurst. 

> It builds tiles and serves isochrones.

And you don’t see https://github.com/valhalla/valhalla/issues/4108?

**Comment by nilsnolde** [comment] 2023-10-23 00:54
This landed now!

**Closed by nilsnolde** 2023-10-23 00:54 UTC

**Comment by zkwurst** [comment] 2023-10-30 20:10
@nilsnolde @kevinkreiser Fantastic! Confirmed the current master branch builds on M1 mac, runs via docker, and outputs isochrones correctly. Thank you!
