### ISSUE TITLE
Debugging tips?

### ISSUE THREAD

**Issue by thomthom** [valhalla/valhalla#4735] opened 2024-05-16 18:27 UTC
When trying to understand what goes on with the routing, any tips at going about with that? Given that a route process a lot of data, what makes life easier?

To give an example:

Here is a route using the Demo app:
![image](https://github.com/valhalla/valhalla/assets/192418/e93acc66-a25a-4716-a69e-cf57a8b77818)
https://valhalla.openstreetmap.de/directions?profile=motorcycle&wps=10.4311589%2C63.4220971%2C12.033720016479494%2C61.887387445382245%2C14.0373946%2C61.2298989%2C13.1929449%2C55.7029296

It's using the `motorcycle` mode with:
```json
{"exclude_polygons":[],"maneuver_penalty":5,"country_crossing_penalty":0,"country_crossing_cost":600,"width":1.6,"height":1.9,"use_highways":0.1,"use_tolls":1,"use_ferry":1,"ferry_cost":300,"use_living_streets":0.5,"use_tracks":0.8,"private_access_penalty":450,"ignore_closures":false,"ignore_restrictions":false,"ignore_access":false,"closure_factor":9,"service_penalty":15,"service_factor":1,"exclude_unpaved":0,"shortest":false,"exclude_cash_only_tolls":false,"top_speed":140,"fixed_speed":0,"toll_booth_penalty":0,"toll_booth_cost":15,"gate_penalty":300,"gate_cost":30,"include_hov2":false,"include_hov3":false,"include_hot":false,"disable_hierarchy_pruning":false,"use_trails":0.8}
```

Now, here is my app, using pyvalhalla, also `motorcycle` mode with similar settings:
![image](https://github.com/valhalla/valhalla/assets/192418/911d3d04-0b89-4202-a260-64e2ec84ff13)

Notice that the routing is very different.
Particular around the two middle points:
![image](https://github.com/valhalla/valhalla/assets/192418/0776e7b0-f3b9-4c9a-91ba-551ea64a60b8)

Now, if all I change is the mode to `auto` then the route looks like this:
![image](https://github.com/valhalla/valhalla/assets/192418/1cb8a447-947a-4370-b8ad-aa151f671441)

This is much closer to the demo app. However, it's not using the same mode. I'd like to understand what causes this big difference in my app. I would have expected the `motorcycle` mode to be similar to the demo app. Especially when `auto` is routing where I expect/want it to.

Any tips to how one goes about debugging such issues?

**Comment by chrstnbwnkl** [comment] 2024-05-21 10:41
This is not really pointing to a concrete issue with Valhalla, so I'm closing it, but feel free to reopen it as a discussion, preferably with a minimal reproducible example (i.e. not a route through entire Scandinavia). If you are using a Docker image, its probably best to open the discussion there as whatever that image does to set you up with a valhalla_service instance probably explains why the results you're getting are different from the demo server ones.

A generally good first step for making sense of routes returned by valhalla would be to look for the smallest possible example where you can observe "unexpected" behavior (whatever that may mean in your specific case) so that you can try to isolate it and maybe go check out the way tags of the corresponding edges along your route (or of the edges that you expected to be used but weren't) on https://openstreetmap.org.

**Closed by chrstnbwnkl** 2024-05-21 10:41 UTC

**Comment by thomthom** [comment] 2024-05-21 18:48
Yea, I wanted to ask generally about how you all debug Valhalla issues so I could do more of that myself.

Do you mostly analyse input and output data? I was wondering if you had a workflow for looking at an issue via the debugger - only some tips on how to deal with the fact that you quickly get quite a bit of data and would need to step alot. For instance, if I wanted to step through the logic as the route calculation is considering a road branch onto where I would expect it to branch but ends up not going there. Are the IDs in the road network I can dig up and set conditional breakpoints for that?

**Comment by kevinkreiser** [comment] 2024-05-22 02:37
yep at a high level the way to attack an issue is first to isolate it to the smallest test case as possible that still shows the problem. once you have there is kind of hierarchy of things to check:

1. OSM - to see if any of the ways/nodes along the way have unexpected tagging
2. valhalla tiles - use the locate demo or gdb a mini tile build of the area to see if we have strange attribution in the created graph nodes and edges
3. move on to debugging the runtime request:
4. first check loki to see what edge candidates we get for the input locations and if they align with our expectations and if the reachability on those makes sense
5. then check thor to see how the expansion takes place. if there is an edge you expect the expansion to touch/use and it doesnt, see if the algorithm checks it and discards it in sif/costing and if not see if the algorithm skips it for any other reasons such as hierarchy culling etc.
6. if the issue is something to do with the output not the path selection you need to look into thor::triplegbuilder, odin or tyr as those primarily control what information you get out of the router along the route.

as the subject is fairly complicated you can imagine there is a lot of room or deviation from a set script for debugging. i generally tend to like debugging with the debugger but others might prefer adding prints to the code and doing it that way. again though it really depends on what exact problem you are facing and then based on that where you suspect you need to look. i can give more details feel free to ask more questions
