### ISSUE TITLE
Preferred side not working on osm data based Valhalla?

### ISSUE THREAD

**Issue by radekvermirovsky** [valhalla/valhalla#4752] opened 2024-06-06 08:31 UTC
Hello,

We are currently running multiple instances of Valhalla. On the instance where we build map data from commercially bought data, the preferred_side parameter works as expected on both the route and matrix endpoints. However, we have discovered that the same request does not respect this parameter on our OSM data-based instance. Both Valhalla setups are nearly identical, with the only difference being the data source.

Our Valhalla instances are based on a master branch from a few weeks ago. We also tested these requests on the public OSM Valhalla instance and encountered the same issue. It appears that the OSM-based Valhalla does not respect the preferred_side parameter even on the public instance.

The issue can be tested at the following URL:
[https://valhalla1.openstreetmap.de/route](url)

Here is the request body:

```
{
	"locations": [
		{
			"lon": 18.163694,
			"lat": 49.611363,
			"preferred_side": "same"
		},
		{
			"lon": 18.164601,
			"lat": 49.610804,
			"preferred_side": "same"
		}
	],
	"costing": "auto",
	"prioritize_bidirectional": true
}
```
The result we get is as follows (which incorrectly places the side of the street on the left, despite being in a right-side driving country like the Czech Republic):
```
{
    "trip": {
        "locations": [
            {
                "type": "break",
                "lat": 49.611363,
                "lon": 18.163694,
                "side_of_street": "left",
                "original_index": 0
            },
            {
                "type": "break",
                "lat": 49.610804,
                "lon": 18.164601,
                "side_of_street": "left",
                "original_index": 1
            }
        ],
        "legs": [
            {
                "maneuvers": [
                    {
                        "type": 3,
                        "instruction": "Drive southeast on 58.",
                        "verbal_succinct_transition_instruction": "Drive southeast. Then Your destination will be on the left.",
                        "verbal_pre_transition_instruction": "Drive southeast on 58. Then Your destination will be on the left.",
                        "verbal_post_transition_instruction": "Continue for 90 meters.",
                        "street_names": [
                            "58"
                        ],
                        "time": 6.242,
                        "length": 0.09,
                        "cost": 6.086,
                        "begin_shape_index": 0,
                        "end_shape_index": 2,
                        "verbal_multi_cue": true,
                        "travel_mode": "drive",
                        "travel_type": "car"
                    },
                    {
                        "type": 6,
                        "instruction": "Your destination is on the left.",
                        "verbal_transition_alert_instruction": "Your destination will be on the left.",
                        "verbal_pre_transition_instruction": "Your destination is on the left.",
                        "time": 0.0,
                        "length": 0.0,
                        "cost": 0.0,
                        "begin_shape_index": 2,
                        "end_shape_index": 2,
                        "travel_mode": "drive",
                        "travel_type": "car"
                    }
                ],
                "summary": {
                    "has_time_restrictions": false,
                    "has_toll": false,
                    "has_highway": false,
                    "has_ferry": false,
                    "min_lat": 49.61068,
                    "min_lon": 18.163537,
                    "max_lat": 49.611265,
                    "max_lon": 18.164401,
                    "time": 6.242,
                    "length": 0.09,
                    "cost": 6.086
                },
                "shape": "c_`s}Actrsa@xG_LvZ_h@"
            }
        ],
        "summary": {
            "has_time_restrictions": false,
            "has_toll": false,
            "has_highway": false,
            "has_ferry": false,
            "min_lat": 49.61068,
            "min_lon": 18.163537,
            "max_lat": 49.611265,
            "max_lon": 18.164401,
            "time": 6.242,
            "length": 0.09,
            "cost": 6.086
        },
        "status_message": "Found route between points",
        "status": 0,
        "units": "kilometers",
        "language": "en-US"
    }
}
```
Polyline of the result:

![image](https://github.com/valhalla/valhalla/assets/149080356/a43f3f9b-bfb4-4ff2-8eab-c05a8b97b576)

However, the expected result should look like this (this is the result of the same request on Valhalla based on commercial map data):

![image](https://github.com/valhalla/valhalla/assets/149080356/9d93da99-4885-403b-8c86-6cc35f7f5324)

It seems that either our OSM-based Valhalla instance and the public Valhalla instance are not configured correctly, or the tiles are not built with all necessary components.

Do you have any idea what could be causing this issue?

Thank you for your assistance.

**Comment by michaelhrabanek** [comment] 2024-06-06 08:53
Looking at history of issues, I've found https://github.com/valhalla/valhalla/issues/4417. It's about a different issue, but using the same request on current master and latest OSM tiles, it seems something has changed in the tiles building process (as with different source data, this works, so it's probably not algorithm related). Currently, Valhalla ignores `preferred_side` on this request, but judging by the screenshot in the mentioned issue, it worked back in November. (I'm assuming @Trietes was using OSM data, but I have no evidence of it.)

**Comment by nilsnolde** [comment] 2024-06-06 09:23
for your osm graph, you sure you built admins correctly? can you try in the UK if you have it in the graph?

**Comment by michaelhrabanek** [comment] 2024-06-06 09:30
Yes, admins are correct, we even checked the requests on public Valhalla before submitting this (I assume admins are correct there, right?). Moreover to exclude the possibility of this being admins issue, we tried with `preferred_side`: "opposite" and the result was the same.

**Comment by nilsnolde** [comment] 2024-06-06 09:36
Oops, yeah, I overread the "public" bit, sorry for the noise:) OSM data itself has little influence here, it's only admin(-/code)-related I believe and yeah, I wouldn't expect them to be broken on the public instance.

**Comment by michaelhrabanek** [comment] 2024-06-06 13:03
> Yes, admins are correct, we even checked the requests on public Valhalla before submitting this (I assume admins are correct there, right?). Moreover to exclude the possibility of this being admins issue, we tried with `preferred_side`: "opposite" and the result was the same.

Oh, scratch that, my bad, I probably messed up the request, as looking at it now again, using `preferred_side`: "opposite" really returns different result.

But in that case this leads to different issue - as in the original issue mentioned 

> The result we get is as follows (which incorrectly places the side of the street on the left, despite being in a right-side driving country like the Czech Republic):

Does this means that graph built with admins is somehow corrupted? Because as I said we're getting same results locally as with  the  valhalla1.openstreetmap.de. Maybe it's related to what @kevinkreiser  said here
https://github.com/valhalla/valhalla/issues/4028#issuecomment-1472339204 that by default (without admins)  left hand driving is assumed?

It's same with the another issue I linked https://github.com/valhalla/valhalla/issues/4417 - it's working 'correctly' if  `preferred_side`: "opposite" is used

**Comment by kevinkreiser** [comment] 2024-06-06 13:07
yeah that would be my guess, that its got the wrong idea about what side of the road is the correct one to drive on. you can find out by using the locate api to click on a node in the graph. the node has a property called `drive_on_right`. check if that look correct, if it does then we'll need to test some other hypotheses

**Comment by michaelhrabanek** [comment] 2024-06-07 05:29
Yes, you're right, that's the root cause:
Using locate on a node in Berlin on public fossgis server:
``` 
https://valhalla1.openstreetmap.de/locate
{ "costing": "auto", "verbose": true, "id": 1, "locations": [ { "lon": 13.401681, "lat": 52.506151, "radius": 2 } ] }
```
is returning
```
   ...
     "administrative": {
                    "time_zone_name": "Europe/Berlin",
                    "state": "Berlin",
                    "iso_3166-2": "BE",
                    "country": "Deutschland",
                    "iso_3166-1": "DE"
                },
                "drive_on_right": false,
   ...
```

**Comment by chrstnbwnkl** [comment] 2024-06-07 06:32
Just had a look at the sqlite from the public instance. I mean Berlin is a crazy place but I don't remember them recently changing the driving side :smile: 

![image](https://github.com/valhalla/valhalla/assets/58629404/f84e7207-04e8-40c1-b326-bde5fedafa84)

Shouldn't this be set to `1` though since Berlin has no entry in the `drive_on_right` table in `admin.lua`?

**Comment by michaelhrabanek** [comment] 2024-06-07 09:52
@chrstnbwnkl it's not Berlin specific btw, looking at Frankfurt
```
{ "costing": "auto", "verbose": true, "id": 1, "locations": [ { "lon": 8.681222, "lat": 50.106814, "radius": 2 } ] }
```
it returns false too
```
   "administrative": {
                    "time_zone_name": "Europe/Berlin",
                    "state": "Hessen",
                    "iso_3166-2": "HE",
                    "country": "Deutschland",
                    "iso_3166-1": "DE"
                },
                "tagged_access": false,
                "density": 12,
                "drive_on_right": false,
```

**Comment by nilsnolde** [comment] 2024-06-07 09:56
it seems to be related with state vs country right? that'd be crazy if a bug of that sort went unnoticed for a supposedly long long time

**Comment by chrstnbwnkl** [comment] 2024-06-07 13:08
Just created Germany admins using a fresh build of `valhalla_build_admins` from latest master, no such issue there.

**Comment by chrstnbwnkl** [comment] 2024-06-18 06:39
Closing this, seems to have been a faulty admin sqlite (possibly related to #4243)

**Closed by chrstnbwnkl** 2024-06-18 06:39 UTC
