### ISSUE TITLE
Build failures with -DENABLE_DATA_TOOLS=OFF

### ISSUE THREAD

**Issue by dnesbitt61** [valhalla/valhalla#2553] opened 2020-08-21 19:16 UTC
Using -DENABLE_DATA_TOOLS=OFF in cmake:

cmake .. -DCMAKE_BUILD_TYPE=Release -DENABLE_PYTHON_BINDINGS=Off -DENABLE_DATA_TOOLS=OFF

Build fails:
Scanning dependencies of target utrecht_tiles
make[2]: *** No rule to make target '../test/valhalla_build_tiles', needed by 'test/data/utrecht_tiles/0/003/196.gph'.  Stop.
CMakeFiles/Makefile2:5840: recipe for target 'test/CMakeFiles/utrecht_tiles.dir/all' failed
make[1]: *** [test/CMakeFiles/utrecht_tiles.dir/all] Error 2

**Comment by mandeepsandhu** [comment] 2020-08-25 18:38
Duplicate of https://github.com/valhalla/valhalla/issues/2496

**Closed by mandeepsandhu** 2020-08-25 18:38 UTC
Labels: bug
