### ISSUE TITLE
Inconsistent behavior on /trace_route between v2 and v3

### ISSUE THREAD

**Issue by jczaplew** [valhalla/valhalla#1838] opened 2019-06-03 20:18 UTC
I recently upgraded from 2.x to 3.0.3(master@1349ca35e862770eac2237effb6b67cc530fb42d) and a test request to `/trace_route` that formerly worked now fails. These tests are done on [an extract of California from GeoFabrik](http://download.geofabrik.de/north-america/us/california-latest.osm.pbf).

For example, a request to `/trace_route` for this line works as expected:

<img width="570" alt="image" src="https://user-images.githubusercontent.com/1739551/58829782-537ee500-860e-11e9-8eb4-fa0c72b9be67.png">

````
curl -d \
'{"encoded_polyline": "o{hjgA`_zbiFyeApyAi\\lpC", "costing": "pedestrian", "shape_match": "walk_or_snap"}' \
-H "Content-Type: application/json" \
-X POST http://localhost:8002/trace_route

{
    "trip":{"language":"en-US","summary":{...}, 
    "status_message":"Found route between points",
    "status":0
}
````

The same line, but with an additional vertex added to the end of the line does not work:

<img width="527" alt="image" src="https://user-images.githubusercontent.com/1739551/58829710-24687380-860e-11e9-96f1-9a0a2ef74a3a.png">

````
curl -d \
'{"encoded_polyline": "o{hjgA`_zbiFyeApyAi\\lpCmcAbG", "costing": "pedestrian", "shape_match": "walk_or_snap"}' \
-H "Content-Type: application/json" \
-X POST http://localhost:8002/trace_route

{
    "error_code": 442,
    "error": "No path could be found for input",
    "status_code": 400,
    "status": "Bad Request"
}
````

However, modifying the previous request to only include the last vertex of the first request and the vertex added in the previous request works:

<img width="518" alt="image" src="https://user-images.githubusercontent.com/1739551/58829938-b2dcf500-860e-11e9-8397-b3b6f49e50a2.png">

````
curl -d \
'{"encoded_polyline": "s_ljgA`kaciFmcAbG", "costing": "pedestrian", "shape_match": "walk_or_snap"}' \
-H "Content-Type: application/json" \
-X POST http://localhost:8002/trace_route
````

I used the [locate demo](https://github.com/valhalla/demos/tree/gh-pages/locate) to inspect the edges used in these requests and there is nothing that sticks out as being problematic:

````json
[
  {
    "edge_id": {
      "id": 10569,
      "value": 354642680362,
      "tile_id": 736069,
      "level": 2
    },
    "edge_info": {
      "shape": "o~jjgAh~~biF?\\?zA]hCsBlJUhBoDzK{@fDm@jBwDnIu@hBaHvMqAxBeAzAwCzAkBNmD\\}EN}D?yGOyBNmFOaC]iB_@iBm@yBMcB\\cAxBGxBt@zAhBl@jGhBxBl@rFjBpBj@nClAjAj@fExCfDvClEdF`BxBzAfCbAhC|@vC\\zAt@tELfDVfD?fDOvCMtD_@xC]fDe@vCm@vCkApH}@~HsApHcA~H{AnHsA`IcAnHe@fDUfDGvC?fDOxC]nH]hCcBnHm@xC]vC}@~HUvCu@xCaBhByB\\yBMaC}@}EyBcFgCsBm@_C}@sB]}D]uEz@sF\\qBxCsApGaCbGu@fCUxC]vCLvC\\xC|@xBzAhB`BhBbBzAbFxCrFhBlEhBzBjAfCjB`ChCjAxBdAfDj@`GsAtOyB~HyBfDmEpHmDvCuEvDmEdEwCpGmAvDNbFnCdF?pGkAdFyBdEe@tEFtDUrFm@`H_@rFk@`RrAbGeAvCm@fD]vDUtDGfDGfDu@`H{@dE_@vDe@fD]tDm@fD]fD{@fD}@fDsAvCcAxCu@tDGvDMtDGvDGtD?vDNdELfD\\vDf@fDd@tDj@fDf@vDDfD?jAEfD_@tD]fDe@vDe@tDu@fDkAhCsAfCyBzAyBzAaCjAiCjAyBjAoC|@iC\\wCMiC_@iBm@cBkAcAyBkAgCcByBaBiCsAiCsAyBeAwC]kAiBeF_DgCaH{AcBkAsFkBmEyAiCm@wCOoC?qC?aCm@aC{@qByBe@}@cAyBsFkKmEsFcLaIkKqGyCgDaB{@mELsA\\m@|@]xBOxBThCt@tDrAfDThCt@fDd@fD?xBMdEm@bFWrGNdEz@vC`CvCvDxCvCxBbBhBrAhCd@fDLfDFtD?fD?fDGvDFfDGfDMdD?vD?fDWvC]vDu@vCyBzAwC\\oC]sA}@cBwCe@wCe@yCe@gC]yCg@wCs@wC}@iC{AiBaBkBqB{@yB}@yBm@aC{@kBkAiBkAiBm@{Bm@aBN{A\\qBz@aCl@qBNsA]qCm@_Cm@{Bm@yB{A{@yBOiCNgC\\gDNgDd@gDd@gDl@gDz@uE|@iLNyC?gD?eD?wDDgDFuD?gDGgDe@gDm@gD{@iCcAwCsAyBcBkBcByAiBkBcAyBWgC\\iCl@wCd@yCVuDTgD?gD]gDwC_SW{A{@eE{AyBcByBaBkBcB{AqByAqB{AkB{AaBiBqB{AkB{AqB{AqBkAyB{@yBm@aC?aC?yBLaC?qBMaCOqBOkBMyAOsA?qCMyB_@}D{@wX_TiC{@aB_@{AMqCLgCMyBOiCOiCMyB]gC_@yB{@iCm@aCm@aCm@yBOiBNqC\\aC^gC?qCOoCOqCMgC_@aCk@iCm@iCm@kA]kA}@aBiBsBkBqBiByBkAiB}@sBm@_CMeALaB^aCj@qCxC",
      "speed_limit": 0,
      "names": [
        "Coast Trail"
      ],
      "bike_network": {
        "mountain": false,
        "local": false,
        "regional": false,
        "national": false
      },
      "mean_elevation": 1234,
      "way_id": 28917734
    },
    "edge": {
      "sidewalk_left": false,
      "not_thru": false,
      "forward": true,
      "bike_network": false,
      "round_about": false,
      "access": {
        "bicycle": true,
        "motorcycle": false,
        "bus": false,
        "car": false,
        "pedestrian": true,
        "emergency": false,
        "truck": false,
        "HOV": false,
        "taxi": false,
        "wheelchair": true,
        "moped": false
      },
      "bridge": false,
      "tunnel": false,
      "destination_only": false,
      "seasonal": false,
      "classification": {
        "internal": false,
        "classification": "service_other",
        "use": "path",
        "surface": "compacted",
        "link": false
      },
      "toll": false,
      "sidewalk_right": false,
      "lane_count": 1,
      "has_exit_sign": false,
      "country_crossing": false,
      "part_of_complex_restriction": false,
      "cycle_lane": "shared",
      "end_restriction": {
        "bicycle": false,
        "motorcycle": false,
        "bus": false,
        "car": false,
        "pedestrian": false,
        "emergency": false,
        "truck": false,
        "HOV": false,
        "taxi": false,
        "wheelchair": false,
        "moped": false
      },
      "geo_attributes": {
        "curvature": 15,
        "length": 3327,
        "weighted_grade": 0,
        "max_up_slope": 0,
        "max_down_slope": 0
      },
      "start_restriction": {
        "bicycle": false,
        "motorcycle": false,
        "bus": false,
        "car": false,
        "pedestrian": false,
        "emergency": false,
        "truck": false,
        "HOV": false,
        "taxi": false,
        "wheelchair": false,
        "moped": false
      },
      "traffic_signal": false,
      "access_restriction": false,
      "truck_route": false,
      "speeds": {
        "predicted": false,
        "default": 10,
        "free_flow": 0,
        "type": "classified",
        "constrained_flow": 0
      },
      "end_node": {
        "id": 56,
        "value": 1884936738,
        "tile_id": 736068,
        "level": 2
      }
    },
    "minimum_reachability": 0,
    "distance": 0.7,
    "percent_along": 0.0654,
    "correlated_lon": -122.750252,
    "side_of_street": "neither",
    "correlated_lat": 37.936436
  },
  {
    "edge_id": {
      "id": 153,
      "value": 5139716642,
      "tile_id": 736068,
      "level": 2
    },
    "edge_info": {
      "shape": "o~jjgAh~~biF?\\?zA]hCsBlJUhBoDzK{@fDm@jBwDnIu@hBaHvMqAxBeAzAwCzAkBNmD\\}EN}D?yGOyBNmFOaC]iB_@iBm@yBMcB\\cAxBGxBt@zAhBl@jGhBxBl@rFjBpBj@nClAjAj@fExCfDvClEdF`BxBzAfCbAhC|@vC\\zAt@tELfDVfD?fDOvCMtD_@xC]fDe@vCm@vCkApH}@~HsApHcA~H{AnHsA`IcAnHe@fDUfDGvC?fDOxC]nH]hCcBnHm@xC]vC}@~HUvCu@xCaBhByB\\yBMaC}@}EyBcFgCsBm@_C}@sB]}D]uEz@sF\\qBxCsApGaCbGu@fCUxC]vCLvC\\xC|@xBzAhB`BhBbBzAbFxCrFhBlEhBzBjAfCjB`ChCjAxBdAfDj@`GsAtOyB~HyBfDmEpHmDvCuEvDmEdEwCpGmAvDNbFnCdF?pGkAdFyBdEe@tEFtDUrFm@`H_@rFk@`RrAbGeAvCm@fD]vDUtDGfDGfDu@`H{@dE_@vDe@fD]tDm@fD]fD{@fD}@fDsAvCcAxCu@tDGvDMtDGvDGtD?vDNdELfD\\vDf@fDd@tDj@fDf@vDDfD?jAEfD_@tD]fDe@vDe@tDu@fDkAhCsAfCyBzAyBzAaCjAiCjAyBjAoC|@iC\\wCMiC_@iBm@cBkAcAyBkAgCcByBaBiCsAiCsAyBeAwC]kAiBeF_DgCaH{AcBkAsFkBmEyAiCm@wCOoC?qC?aCm@aC{@qByBe@}@cAyBsFkKmEsFcLaIkKqGyCgDaB{@mELsA\\m@|@]xBOxBThCt@tDrAfDThCt@fDd@fD?xBMdEm@bFWrGNdEz@vC`CvCvDxCvCxBbBhBrAhCd@fDLfDFtD?fD?fDGvDFfDGfDMdD?vD?fDWvC]vDu@vCyBzAwC\\oC]sA}@cBwCe@wCe@yCe@gC]yCg@wCs@wC}@iC{AiBaBkBqB{@yB}@yBm@aC{@kBkAiBkAiBm@{Bm@aBN{A\\qBz@aCl@qBNsA]qCm@_Cm@{Bm@yB{A{@yBOiCNgC\\gDNgDd@gDd@gDl@gDz@uE|@iLNyC?gD?eD?wDDgDFuD?gDGgDe@gDm@gD{@iCcAwCsAyBcBkBcByAiBkBcAyBWgC\\iCl@wCd@yCVuDTgD?gD]gDwC_SW{A{@eE{AyBcByBaBkBcB{AqByAqB{AkB{AaBiBqB{AkB{AqB{AqBkAyB{@yBm@aC?aC?yBLaC?qBMaCOqBOkBMyAOsA?qCMyB_@}D{@wX_TiC{@aB_@{AMqCLgCMyBOiCOiCMyB]gC_@yB{@iCm@aCm@aCm@yBOiBNqC\\aC^gC?qCOoCOqCMgC_@aCk@iCm@iCm@kA]kA}@aBiBsBkBqBiByBkAiB}@sBm@_CMeALaB^aCj@qCxC",
      "speed_limit": 0,
      "names": [
        "Coast Trail"
      ],
      "bike_network": {
        "mountain": false,
        "local": true,
        "regional": true,
        "national": true
      },
      "mean_elevation": 1234,
      "way_id": 28917734
    },
    "edge": {
      "sidewalk_left": false,
      "not_thru": false,
      "forward": false,
      "bike_network": false,
      "round_about": false,
      "access": {
        "bicycle": true,
        "motorcycle": false,
        "bus": false,
        "car": false,
        "pedestrian": true,
        "emergency": false,
        "truck": false,
        "HOV": false,
        "taxi": false,
        "wheelchair": true,
        "moped": false
      },
      "bridge": false,
      "tunnel": false,
      "destination_only": false,
      "seasonal": false,
      "classification": {
        "internal": false,
        "classification": "service_other",
        "use": "path",
        "surface": "compacted",
        "link": false
      },
      "toll": false,
      "sidewalk_right": false,
      "lane_count": 1,
      "has_exit_sign": false,
      "country_crossing": false,
      "part_of_complex_restriction": false,
      "cycle_lane": "shared",
      "end_restriction": {
        "bicycle": false,
        "motorcycle": false,
        "bus": false,
        "car": false,
        "pedestrian": false,
        "emergency": false,
        "truck": false,
        "HOV": false,
        "taxi": false,
        "wheelchair": false,
        "moped": false
      },
      "geo_attributes": {
        "curvature": 15,
        "length": 3327,
        "weighted_grade": 0,
        "max_up_slope": 0,
        "max_down_slope": 0
      },
      "start_restriction": {
        "bicycle": false,
        "motorcycle": false,
        "bus": false,
        "car": false,
        "pedestrian": false,
        "emergency": false,
        "truck": false,
        "HOV": false,
        "taxi": false,
        "wheelchair": false,
        "moped": false
      },
      "traffic_signal": false,
      "access_restriction": false,
      "truck_route": false,
      "speeds": {
        "predicted": false,
        "default": 10,
        "free_flow": 0,
        "type": "classified",
        "constrained_flow": 0
      },
      "end_node": {
        "id": 4322,
        "value": 145028143658,
        "tile_id": 736069,
        "level": 2
      }
    },
    "minimum_reachability": 0,
    "distance": 0.7,
    "percent_along": 0.9346,
    "correlated_lon": -122.750252,
    "side_of_street": "neither",
    "correlated_lat": 37.936436
  }
]
````

This behavior seems to be isolated to `/trace_route` in v3.x, as `/route` in both v2 and v3 and `/trace_route` in v2.x work as expected for all of the above examples. While trying to isolate this issue I came across a few instances where the request would fail when using `"shape_match": "map_snap"`, but succeed with `"shape_match": "walk_or_snap"`. I tried specifying `"trace_options": {"search_radius": 100}` to see if that would change the results but I did not come across any scenario in which it made a failing request succeed. 

Are there any new settings or configurations introduced in v3 that would produce this behavior?

**Comment by kevinkreiser** [comment] 2019-06-04 18:48
we've been doing some refactoring there lately so this could be some collateral damage! we'll have to take a look and see what is going on. thanks for reporting the regression!

**Comment by danpaz** [comment] 2019-06-09 21:44
I was able to reproduce locally and added some logging to trace_route's exception handling:

```
19 2019/06/09 21:39:33.217161 POST /trace_route HTTP/1.1
2019/06/09 21:39:33.217778 [INFO] Got Loki Request 19
2019/06/09 21:39:33.218528 [ANALYTICS] costing_type::pedestrian
2019/06/09 21:39:33.218780 [ANALYTICS] trace_size::4
2019/06/09 21:39:33.218890 [ANALYTICS] location_distance::0.455808km
2019/06/09 21:39:33.222409 [INFO] Got Thor Request 19
2019/06/09 21:39:33.222596 [ANALYTICS] travel_mode::1
Process 3418 stopped
* thread #2, name = 'ZMQbg/5', stop reason = breakpoint 1.1
    frame #0: 0x000000010098abe4 valhalla_service`valhalla::thor::thor_worker_t::trace_route(this=0x00007000080202d0, request=0x000070000801fab8) at trace_route_action.cc:90:63
   87         try {
   88           map_match(request);
   89         } catch (const std::exception& e) {
-> 90           valhalla::midgard::logging::Log("400::" + std::string(e.what()), " [ANALYTICS] ");
   91         }
   92         break;
   93       // If we think that we have the exact shape but there ends up being no Valhalla route match,
Target 0: (valhalla_service) stopped.
(lldb) c
Process 3418 resuming
2019/06/09 21:39:34.752048 [ANALYTICS] 400::GraphTile NodeInfo index out of bounds: 736069,2,4322 nodecount= 85
2019/06/09 21:39:34.752172 [WARN] thor::trace_route request elapsed time (ms)::1529.762939
2019/06/09 21:39:34.752192 [WARN] thor::trace_route request exceeded threshold::19
2019/06/09 21:39:34.752202 [ANALYTICS] valhalla_thor_long_request_trace_route
2019/06/09 21:39:34.752579 [INFO] Got Odin Request 19
[libprotobuf FATAL /usr/local/include/google/protobuf/repeated_field.h:1522] CHECK failed: (index) < (current_size_): 
19 2019/06/09 21:39:34.753076 400 246
```

The thrown exception was `GraphTile NodeInfo index out of bounds: 736069,2,4322 nodecount= 85`. Not sure what to make of that error yet.

**Comment by dnesbitt61** [comment] 2019-06-10 04:42
Since this started at Valhalla 3it could be due to invalid NodeTransition logic, though nothing seems wrong in meili/routing.cc at first glance (comparing to thor/astar.cc)

**Comment by jczaplew** [comment] 2019-06-27 21:47
If there is anything I can do to help debug this issue please let me know!

**Comment by kevinkreiser** [comment] 2019-06-27 23:37
@jczaplew im looking into this now. i'll keep you posted, thanks for the excellent reproduction steps.

**Comment by kevinkreiser** [comment] 2019-06-28 15:01
seems there was a copy paste fail when we did valhalla v3: https://github.com/valhalla/valhalla/pull/1648/files#diff-071866e4347d1551fe1854ea1e40ae37R579

we get the endnode tile but then reuse the edges tile to look up the shape for the node. a simple mistake but it will error the request when matching across tile boundaries. ill have a fix for this shortly.

**Closed** 2019-06-28 18:03 UTC
Labels: bug

**Comment by jczaplew** [comment] 2019-06-28 18:07
Fantastic, thank you so much! Really appreciate it.
