### ISSUE TITLE
Valhalla crash when calling isochrone endpoint

### ISSUE THREAD

**Issue by robhawkes** [valhalla/valhalla#858] opened 2017-07-28 17:19 UTC
I've loaded up Valhalla using the [New Zealand extract from Geofabrik](http://download.geofabrik.de/australia-oceania/new-zealand.html). The routing endpoint works great but whenever I try an isochrone Valhalla crashes with the following output:

```
$ valhalla_route_service valhalla.json 1
2017/07/28 17:13:17.115527 [INFO] Tile extract successfully loaded
0 2017/07/28 17:13:26.815705 GET /isochrone?json=%7B%22locations%22:%5B%7B%22lat%22:%22-44.69135583616529%22,%22lon%22:%22169.17503356933594%22%7D%5D,%22costing%22:%22auto%22,%22denoise%22:0.3,%22polygons%22:true,%22generalize%22:50,%22costing_options%22:%7B%22pedestrian%22:%7B%22use_ferry%22:0%7D,%22bicycle%22:%7B%22use_ferry%22:0%7D%7D,%22contours%22:%5B%7B%22time%22:15%7D,%7B%22time%22:30%7D,%7B%22time%22:45%7D,%7B%22time%22:60%7D%5D%7D HTTP/1.1
2017/07/28 17:13:26.816085 [INFO] Got Loki Request 0
2017/07/28 17:13:26.816291 [ANALYTICS] locations_count::1
2017/07/28 17:13:26.816302 [ANALYTICS] costing_type::auto
2017/07/28 17:13:26.816343 [ANALYTICS] max_location_distance::0.000000km
2017/07/28 17:13:26.817078 [INFO] Got Thor Request 0
2017/07/28 17:13:26.817232 [ANALYTICS] travel_mode::0
dyld: lazy symbol binding failed: Symbol not found: __ZNSt3__16vectorIN8valhalla5baldr12PathLocationENS_9allocatorIS3_EEED1Ev
  Referenced from: /Users/robin/valhalla/.libs/libvalhalla.0.dylib
  Expected in: flat namespace

dyld: Symbol not found: __ZNSt3__16vectorIN8valhalla5baldr12PathLocationENS_9allocatorIS3_EEED1Ev
  Referenced from: /Users/robin/valhalla/.libs/libvalhalla.0.dylib
  Expected in: flat namespace

[1]    48943 abort      valhalla_route_service valhalla.json 1
```

What can I do to help debug this?

## Useful information

* MacOS 10.12.5
* Valhalla built from source [using readme instructions](https://github.com/valhalla/valhalla#building-from-source)
* Tiles created using the following commands
```
valhalla_build_config --mjolnir-tile-dir ${PWD}/valhalla_tiles --mjolnir-tile-extract ${PWD}/valhalla_tiles.tar --mjolnir-timezone ${PWD}/valhalla_tiles/timezones.sqlite --mjolnir-admin ${PWD}/valhalla_tiles/admins.sqlite > valhalla.json

valhalla_build_tiles -c valhalla.json new-zealand-latest.osm.pbf

find valhalla_tiles | sort -n | tar cf valhalla_tiles.tar --no-recursion -T -
```

**Comment by robhawkes** [comment] 2017-07-28 17:31
So I took the tiles created by my local build and gave them to the Valhalla Docker container and that worked fine so the original issue seems to be related to a custom (non-Docker) build of Valhalla. I imagine I've done something wrong so any help with debugging this would be appreciated.

**Comment by kevinkreiser** [comment] 2017-07-31 13:41
@robhawkes im sorry but the core team here doesnt actually use macs (we actually dont have any) so reproducing this is going to be very difficult to say the least... i'm wondering if there is anything wonky with your homebrew, is it possibly for you to update it (grasping at straws here i know). do you have any colleges who'd be willing to try to build it to see if they can reproduce it as well? we'll see if we can find someone to try it out on their hardware too.

**Comment by dnesbitt61** [comment] 2018-09-05 14:36
closing this due to age. if still a problem a new issue can be opened.

**Closed by dnesbitt61** 2018-09-05 14:36 UTC
