### ISSUE TITLE
Map-Matching - Error Rejecting High Speed Paths

### ISSUE THREAD

**Issue by dnesbitt61** [valhalla/valhalla#900] opened 2017-08-22 14:46 UTC
Paths in map-matching are not being rejected based on estimated time vs. measurement time due to interpolated points (points close to one another).  Several examples have the first time followed by some measurements at basically the same position (interpolated) - but the map-matching route rejection uses the time difference between the first point and the next non-interpolated point even though the vehicle was stationary for some period of time leading to a higher max_cost. This diagram perhaps helps (s is a real measurement and i is an interpolated measurement)

...            .       .      ...               ...              Input measurements 
sii            s     s      sii               sis            Current
iis            s     s      sis              sis             Proposed

(... indicates measurements within the interpolation distance, s indicates a "real" measurement and i indicates an interpolated measurement)
With the proposed change the time between the first 2 real non-interpolated measurements will be shorter (from the last of the nearby measurements rather than the first).  Intermediate measurements need to have an "entering" real measurement and a "leaving" real measurement in the grouping of nearby input measurements.

@ptpt @kevinkreiser

**Comment by kevinkreiser** [comment] 2017-08-25 14:12
so i have a few examples of real data exposing this problem. and i can confirm that exactly what is happening is as you describe above. basically because we always use the time from first of the series of close points it looks like the vehicle was on a given sub route for a reasonable amount of time. however after we then interpolate the times for the interpolated close points it looks like a subsection of that route was done insanely fast, way faster than the route would have allowed. so this is completely confirmed.

the immediate idea as you described it above would be to chose the interpolated and interpolated points in such a way as to always use the most relevant times on either side of the route. this is the more conservative approach as it will throw away data that looks impossible.

interestingly though while i was looking at real examples, all of them seem to actually be pretty well behaved routes but just that the coordinates seem to get stuck for a couple of gps updates. this makes me wonder if, for the purpose of traffic matching, we could ignore interpolated points. doing so would allow the routes and essentially ignore the duplicates. i dont think this is such a good idea as you cant be sure what is going and so taking the conservative approach is safer. i just wanted to mention what im seeing.

**Comment by dnesbitt61** [comment] 2017-08-25 16:01
I definitely think the interpolated/duplicate measurements are needed for traffic. I think the main issue is that the meili route needs the time from the last interpolated measurement (rather than the first) so the rejection by time is made properly.

**Comment by kevinkreiser** [comment] 2017-08-25 16:13
my point was that the duplicates look erroneous to me. using the time from the appropriate interpolated point will remove too fast segments but in these cases those segments are too fast because their time was piled up on the previous segment and so that  segment wont get rejected and will be kept and indeed will actually be slower than it should be and we cant reject that.

so i was thinking further that if we can detect when a person basically stops, that we should insert a discontinuity where they stop, this would reject (it will be partial) the too slow one and the too fast one.

**Comment by dnesbitt61** [comment] 2017-08-25 17:15
But for traffic we need to detect stop and go conditions.

**Comment by ptpt** [comment] 2017-08-25 17:16
The proposed change makes sense to me.

What about interpolating measurements in a range of time instead of distance?

**Comment by kevinkreiser** [comment] 2017-08-25 17:25
right but we cant tell the difference of stopping for traffic and stopping for any other reason. 

im not suggesting we dont do the suggestion (im currently working on it). im just suggesting that the data we are seeing seems suspicious and we cant tell if there was slowdown there or not.

**Closed** 2017-08-31 10:43 UTC
Labels: enhancement, meili
