### ISSUE TITLE
North America tile build failed with Exceeding kMaxLinkEdges in ReclassifyLinks

### ISSUE THREAD

**Issue by j-bbr** [valhalla/valhalla#3908] opened 2023-01-13 12:28 UTC
Looks similar to #3473. I was trying to build tiles for North America (pbf extracts from GeoFabrik for North America, Canada, Mexico and Greenland) and the docker container (latest image from gis-ops/docker-valhalla/valhalla) terminated with Exceeding kMaxLinkEdges in ReclassifyLinks.

**Comment by nilsnolde** [comment] 2023-01-13 13:26
The open server started another tile build a few hours ago. If some data change happened that makes this fail again. But honestly.. > 32 link connections to a single edge sounds entirely ludicrous and I hope it's "just" some vandalism.

**Comment by nilsnolde** [comment] 2023-01-13 13:40
> Is the lat,lng where this occurs logged? 

Nope, I did that back then in the planet build but didn't commit to the branch. I didn't figure we'd ever encounter that again :sweat_smile: If the planet fails tmrw, which it should, I'll do that again and this time that log will be merged;)

**Comment by j-bbr** [comment] 2023-01-13 13:42
I'll retry this over the weekend again, and will report back. I saw that you raised the question @nilsnolde whether this limit was necessary at all?

**Comment by nilsnolde** [comment] 2023-01-13 13:51
I guess you don't have to try with the same data again, though thanks for the offer @j-bbr. I'll let you know what comes out of the planet build. 

I'm not sure anymore about all the interactions with that constant, will have a look next week if no one else does. Surely there has to be a limit, but I'm not sure if we could open it up to smth like max of uint8_t or so.

**Comment by j-bbr** [comment] 2023-01-13 13:57
Regarding rerunning the tile build and logging the location where this occurs how would I go about doing this (other than building with the verbose flag)? I apologize but I am not that familiar with valhalla.

**Comment by nilsnolde** [comment] 2023-01-13 14:06
You’ll likely see in the PR next week:) Or just follow that constant in the code base, it’s not used very often. Of course you can just change the value right now and compile Valhalla with that, but that could lead to other problems. Build instructions are in the README.

**Comment by j-bbr** [comment] 2023-01-13 14:11
@nilsnolde No I meant the latitude, longitude where it fails the kMaxLinkEdges constraint. Can that be gathered from the logs somehow? It's not in the (verbose) output.

**Comment by nilsnolde** [comment] 2023-01-13 15:07
No it’s not logged, see my comment here https://github.com/valhalla/valhalla/issues/3908#issuecomment-1381863259

**Comment by nilsnolde** [comment] 2023-01-14 11:58
So the planet just finished building successfully. It pulled fresh OSM data a few hours before the OP. Either it was vandalism indeed or you're on a very old image @j-bbr . If you try again and it doesn't work it's the latter I guess.

**Closed by nilsnolde** 2023-01-14 11:58 UTC

**Comment by j-bbr** [comment] 2023-01-15 14:12
I started a build this morning with the latest (updated yesterday, 14.01.2023) geofabrik extracts for North America, Canada, Mexico and Greenland and it failed again with exceeding kMaxLinkEdges. The image is gis-ops/docker-valhalla/valhalla:latest so it shouldn't be due to an old build. If I can provide any additional information let me know.

**Comment by nilsnolde** [comment] 2023-01-15 14:22
Hm, strange.. Sorry, still gotta ask to make sure: you definitely recently pulled the `latest` image? Can you show us what `docker inspect -f '{{ .Created }}' gisops/valhalla:latest` reports?

**Comment by j-bbr** [comment] 2023-01-15 14:32
I don't have it running locally but here is the version output:
```
Image:          ghcr.io/gis-ops/docker-valhalla/valhalla:latest
Image ID:       ghcr.io/gis-ops/docker-valhalla/valhalla@sha256:8cee2e6b32cbaac3be7dff1428446a190d9fb1d2c3eb8910881f40cbdb7212b8
```

**Comment by nilsnolde** [comment] 2023-01-15 14:44
Matches yesterday's build, so that shouldn't happen. 

Can I ask you to try again, but slightly alter Valhalla code (i.e. a local build: https://valhalla.github.io/valhalla/building/) and apply this patch:
```diff
diff --git a/src/mjolnir/linkclassification.cc b/src/mjolnir/linkclassification.cc
index 9f35f2d02..c241837b2 100644
--- a/src/mjolnir/linkclassification.cc
+++ b/src/mjolnir/linkclassification.cc
@@ -414,7 +414,8 @@ struct LinkGraphBuilder {
 
     // Make sure that number of children does not exceed the threshold
     if (graph_[from].children.size() >= kMaxLinkEdges) {
-      throw std::runtime_error("Exceeding kMaxLinkEdges in ReclassifyLinks");
+      auto ll = graph_[to].bundle.node.latlng();
+      throw std::runtime_error("Exceeding kMaxLinkEdges in ReclassifyLinks at location " + std::to_string(ll.lng()) + "," + std::to_string(ll.lat()));
     }
 
     graph_[to].parents.push_back(from);
```

(easiest to save the contents to file e.g. "patch.diff" and do a `git apply patch.diff` on current `master`)

With the patch, it'll report the node's lon/lat, then we can see what's happening there in OSM data.

**Comment by nilsnolde** [comment] 2023-01-15 15:24
Forget it, I quickly PR'd the log statement. Once it's merged, I'll trigger a fresh image build for our `latest` image. Then you can update and run it, much easier on your side.

**Comment by j-bbr** [comment] 2023-01-15 19:16
I appreciate it @nilsnolde and I'll let you know how the build goes with the new image once it is out.

**Comment by nilsnolde** [comment] 2023-01-16 18:48
Can you try again @j-bbr ? It just finished building `latest` which should tell us at which location your build is failing.

**Comment by j-bbr** [comment] 2023-01-17 19:33
Hi @nilsnolde,
here it is:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Exceeding kMaxLinkEdges in ReclassifyLinks at location -117.029020,32.541797
/valhalla/scripts/configure_valhalla.sh: line 172:    51 Aborted                 (core dumped) valhalla_build_tiles -c ${CONFIG_FILE} -e build ${files}
```
Seems to be the same spot (or very close) to the one you reported in #3473.

**Comment by j-bbr** [comment] 2023-01-19 08:17
Hi @nilsnolde,
regarding the old image, that would be quite unlikely since you included the above debug code only in the latest image right? But I've got another idea: Since it's right on the border between Mexico and US the edges and/or nodes are probably included in both the US and Mexico Geofabrik extracts. So maybe depending on how and where deduplication happens in the tile build process and where the link constraint is enforced this would get a different edge-count than in OSM. I've since build tiles successfully from just the US pbf extract and I am building tiles from just the Mexico pbf extract as well. If this also succeeds then we should know (in a few hours) whether it's due to the combination or just the Mexico pbf extract.

**Comment by nilsnolde** [comment] 2023-01-19 08:30
Hahaha of course, the debug log😂 thanks for the making the obvious obvious:)

Ah sorry I must’ve misunderstood, I thought you processed whole NA at once, not stitching separate PBFs. I’m a bit unsure how dups are handled, there are times when multiple PBFs are failing. It’s always better I believe to make one PBF out of them with osmium or so. Is it possible for multiple PBFs to lead to this issue @gknisely @kevinkreiser?

That being said, I guess it’s Mexican data which was the problem, but depending on Geofabriks extents (which are very coarse), I’d also expect that the US extract contains the problematic ones. Did you check?

**Comment by kevinkreiser** [comment] 2023-01-19 14:26
when you use two extracts that overlap we duplicate the edges for sure, but i also thought we duplicated the nodes. if the nodes are duplicated you wouldnt hit this issue but its possible that we dont duplicate the nodes since i refactored the parsing a couple years ago.

at this immediate moment i like the suggestion of merging the two pbfs before building tiles, but it is true that we could make the parsing robust to duplicates down the road. maybe its worth a feature request issue but it will definitely be lower priority in my opinion

**Comment by j-bbr** [comment] 2023-01-19 19:29
The mexico.pbf tile build completed successfully, so I think it is quite certain that is just happening due to the combination of those two. Probably the overlap and (de)duplication.

Speaking as a user of valhalla, I quite like the functionality of giving separate pbfs to valhalla to build one tar and the way it is exposed in @nilsnolde docker image. So far I have been and am running quite a lot of combinations of extracts successfully. It wouldn't kill me to include a pre-processing step of merging with osmium either but if the kMaxLinkEdges limit can be safely increased as it seems from @dnesbitt61 answer in #3483 to something like 128 so that the overlap scenario is covered as well then that seems like the quick fix to me. But of course no idea whether that has other consequences.

**Comment by nilsnolde** [comment] 2023-01-19 19:45
Yeah those other consequences is what I’d fear without one of us diving deeper. It looks like a bug, but maybe it’s only one way it shows and a much more disastrous symptom is not even showing properly, even if we increase the limit again. As @kevinkreiser pointed out, it’s indicating smth doesn’t seem to work as expected and no one knows what else is lurking there.

I personally vote not to “hot fix” this for now and rather inform people (with a pinned issue or temp in the README), that they shouldn’t use multiple PBFs for now. It’s trivial to preprocess into one. Of course, unless someone has the time to take a closer look and verify what’s happening. Or just remove the option altogether and the headache that comes with (de)duplication of data, bcs it is so trivial I personally think it’s fine to put that responsibility on the user. One could argue a major version change since that’s quite a change of behavior many people have probably running like that. Also there I’d argue it’s better to have them fail than run into unknown bugs.

**Comment by nilsnolde** [comment] 2023-01-19 19:48
I remember that over the past year or two there were several reports of things working all of a sudden when people were merging PBFs (wouldn’t find any..).


Should we think about removing multiple PBFs as input @kevinkreiser @dnesbitt61 and others? Or too aggressive for your taste?

**Comment by dnesbitt61** [comment] 2023-01-19 20:04
I would favor removing support for multiple pbf inputs as long as we document/prescribe the approach for merging them.

**Comment by kevinkreiser** [comment] 2023-01-19 22:03
I think we should take a look at what's happening before removing support. it would be a shame to spend time removing something when that effort could have gone into understanding what is up.

**Comment by nilsnolde** [comment] 2023-01-19 22:21
While I kind of agree it'd be cool to have it if it were for free, I think it does come at a maintenance cost, hence this issue.

To start with, it'd not be much of an effort, effectively only remove support for multiple positional arguments to the executables. Then it's sorted that no one can use that feature, so the user would be "fine", but we'd still have the tech debt to remove associated code. Meeh..

Should we just pin an issue for now, so people have the chance to be aware of it and maybe we have the time to look at it together in one of our meetings in the next weeks?

**Comment by kevinkreiser** [comment] 2023-01-19 23:40
I get that disabling it easy but I'm also not convinced that it's hopelessly broken. for one we didn't even check into it, we are theorizing and secondly we only have this one issue where we are fairly sure it's the cause of problems. seems drastic to removing on a theory about a single issue rather than to check first. if we had tons of issues where we looked and it was the cause I think it'd make more sense. as it is we have one edge case right?
