### ISSUE TITLE
Map-Matching: Return top "k" paths

### ISSUE THREAD

**Issue by dnesbitt61** [valhalla/valhalla#823] opened 2017-07-10 19:15 UTC
For short traces (trace_attribute only) allow multiple "alternate" paths to be returned along with each path having a confidence score. Involves updating Viterbi search. API input has addition of max. number of results (default is 1 with no alternates found). Service limit on max. number of alternates and possible limit to number of points in the trace or their length.

**Comment by dgearhart** [comment] 2017-07-13 13:02
https://github.com/valhalla/valhalla/blob/master/valhalla/meili/map_matcher.h#L47-L48
@ptpt As per our discussion yesterday - I am assuming that the above method will return: std::vector<std::vector<MatchResult>>
Do you agree?

**Comment by ptpt** [comment] 2017-07-13 13:16
@dgearhart yes, don't forget the `k`:
```c++
std::vector<std::vector<MatchResult>>
OfflineMatch(const std::vector<Measurement>& measurements, uint32_t k = 1);
```

**Comment by ptpt** [comment] 2017-07-13 13:20
and the size of the result lists will be no larger than `k`.

**Comment by dgearhart** [comment] 2017-07-13 13:26
@ptpt yep - thank you

**Comment by dgearhart** [comment] 2017-07-13 13:59
@ptpt What are your thoughts about the confidence score? Will a confidence score for the path be returned along with the MatchResult vector?

**Comment by dgearhart** [comment] 2017-07-13 15:09
### Proposed output for `trace_attributes` to include the confidence score and alternate paths
```json
{
   "units": "<units>",
   
   "confidence_score": <confidence_score>,
   "admins": [...],
   "edges": [...],
   "matched_points": [...],
   "shape": "<shape>",
   "osm_changeset": <osm_changeset>,
   "alternate_paths": [
      {
         "confidence_score": <confidence_score>,
         "admins": [...],
         "edges": [...],
         "matched_points": [...],
         "shape": "<shape>",
         "osm_changeset": <osm_changeset>,
      }
   ]

**Comment by dgearhart** [comment] 2017-07-13 18:34
### Proposed input option and service limits for k-best paths
##### option
```
“best_paths”: <uint>
```

##### service_limits
```
“max_best_paths”: 4
“max_best_paths_shape”: 100
```

**Comment by ptpt** [comment] 2017-07-14 10:33
@dgearhart that API makes sense!

Some thoughts on the confidence score: we have a cost asscoiated with each match in the viterbi algorithm, and we compare these costs for finding the best match. We can use normalized costs as the confidence scores, i.e. `each match's score = this match's cost / sum of **all match** costs`.

The question is how we should define "all matches", given a sequence of measurements. i.e. what do we expect `OfflineMatch(measurements, +Infinity)` to return. Should we count a broken match in (a match with at least one breakage, i.e. two successive match results are disconnected)?

- If we count it in, there will be too many possible matches, without considering connections between match results.

- If we don't count it in, then `OfflineMatch(measurements, 1)` will return nothing if the best match is broken. Also sometimes such a broken match doesn't look bad at all on the map -- especially when the breakage is caused by the disconnected road segments in the underlying road network.

I will send more input here later.

**Comment by dgearhart** [comment] 2017-07-14 12:26
@ptpt thanks
@dnesbitt61 @kevinkreiser thoughts on confidence score calculation?

**Comment by kevinkreiser** [comment] 2017-07-14 12:35
i would define all matches as just the top k matches, the rest of the matches dont need to factor into the score computation. i was also hoping we could count broken ones and where the breakage occurs we could compute a cost of straight line distance at a minimum speed or something? otherwise i think exactly what @ptpt proposed sounds like what i was thinking regarding score computation.

**Comment by ptpt** [comment] 2017-07-14 12:52
@kevinkreiser but if we define all as top k, then the scores will vary by k; `OfflineMatch(measurements, 3)` and `OfflineMatch(measurements, 4)` would give different scores. Does it matter?

**Comment by kevinkreiser** [comment] 2017-07-14 13:08
that is correct. i didnt think it was important that the score be globally (over all paths) unique. since the result will be used by a single client to make a decision it seems unlikely the client will call back in with a different `k` and then compare the previous scores. what do @dnesbitt61 and @dgearhart think?

**Comment by ptpt** [comment] 2017-07-14 13:20
Another possible solution is that: we add a new method `OfflineMatchTopK`, while we keep the `OfflineMatch` unchanged. The new method only returns at most `k` unbroken matches. If you are still interested in broken matches when it returns nothing, we provide a util that can split the measurement list to make sure the sub lists are not broken, and send these sub lists to `OfflineMatchTopK` to get their scores respectively.

**Comment by ptpt** [comment] 2017-07-14 13:34
@kevinkreiser the question is that how to calculate a broken match's cost. A broken match has multiple costs while a unbroken match has a single cost. In a more complicated case, if the top k contains both unbroken matches and broken matches, how should we normalize them.

**Comment by kevinkreiser** [comment] 2017-07-14 13:39
@ptpt what i was suggesting was that because we dont have cost for traversing the break in the broken match, that we give it an estimated cost for that section as the slowest speed to travel the portion of the trace that was unmatched. if timestamps are given we could even simply get the cost based on the elapsed time between time stamps, or we could do what i said before which is just use the straight line distance between the two matched points multiplied by the slowest speed this mode of travel could be expected to go, maybe pedestrian would be 1 m/s for example. basically im saying where the breaks exist we come up with a cost so we can measure them the same way we measure the unbroken matches

**Comment by ptpt** [comment] 2017-07-14 13:48
Okay! Make sense to me.

**Comment by ptpt** [comment] 2017-08-02 15:21
This is the k-shortest path algorithm I proposed: http://www.sciencedirect.com/science/article/pii/0377221784902698

**Comment by kevinkreiser** [comment] 2017-08-02 15:53
here are some papers related to it: http://www.mat.uc.pt/~eqvm/cientificos/investigacao/r_papers.html

**Comment by ptpt** [comment] 2017-08-02 18:15
Some thoughts on the interface design:

```c++
class TopKSearch {
    TopKSearch(IViterbiSearch& vs);
    // remove current optimal path in vs_, and maintain the enlarged graph
    void Next();
private:
    IViterbiSearch& vs_;
}
```

Possible usage in `MapMatcher::OfflineMatch`:
```c++
std::vector<std::vector<MatchResult>> result_lists;
TopKSearch topk(mapmatching_);
while (0 <= k) {
    result_lists.push_back(FindResults(mapmatching_.SearchPath(time)));
    topk.Next();
}
return result_lists;
```

**Comment by ptpt** [comment] 2017-08-03 08:11
The one above looks too simple to be true. In `TopKSearch` we can enlarge `vs_`'s graph by adding cloned states to it with `vs_.AddStateId` but we also want to change the way it calculates costs to consider these cloned states. Perfectly we want `TopKSearch` to replace `vs_.TransitionCost` with this new function:

```c++
public:
TopKSearch(IViterbiSearch& vs): vs_(vs) {
    NewTransitionCost(lhs, rhs) {
        if (lhs in the cloned_states_) {
           lhs = cloned_states[lhs]
        }
        if (rhs in the cloned_states_) {
           rhs = cloned_states[lhs]
        }
        return vs_.TransitionCost(lhs, rhs);
    }

    vs_.TransitionCost = NewTransitionCost;
}
private:
// map cloned stateids -> original stateids
std::unordered_map<StateId, StateId> cloned_states_;
```

Apparently we can't do that in C++ :). Need to rethink.

**Comment by ptpt** [comment] 2017-08-18 16:41
In progress now.

The solution might be to make the methods replaceable:

```c++
using EmissionCostingMode = std::function<float(const StateId& stateid)>;
using TransitionCostingMode = std::function<float(const StateId& lhs, const StateId& rhs)>;

class IViterbiSearch {
public:
  EmissionCostingMode emission_costing_mode;
  TransitionCostingMode transition_costing_mode;
}
```

**Comment by ptpt** [comment] 2017-08-29 10:33
In progress in this PR https://github.com/valhalla/valhalla/pull/909

One question: How large would the 'k' be usually?

**Comment by kevinkreiser** [comment] 2017-08-29 10:35
@ptpt I would imagine it to be small, less than 10 probably more like 3 for practical use.

**Comment by ptpt** [comment] 2017-09-01 11:23
Theorically, what would you expect the topk search algorithm to return if there exists only one path but you ask for 2 (k=2)?

Say we have a trivial graph that has only one path from left to right:
```
1 -> 2 -> 3 -> 4
```

According to @kevinkreiser's suggestion, if we weight breakages between states with a large cost, then we would expect the 2nd best path to be same as `1 -> 2 -> 3 -> 4` but with a broken edge in it, which leads to a larger path cost than 1st best path.

**Comment by kevinkreiser** [comment] 2017-09-01 12:21
yeah i was thinking of this yesterday.. what if we have it throw, catch the exception and stop the k loop and just return less results. i dont think there is anything wrong with having less than k results.

**Comment by dnesbitt61** [comment] 2017-09-01 12:45
Definitely fine to have less than k results. Most of the time these should be short traces and often only 1 result is even possible - so only 1 should be returned in that case.

**Comment by ptpt** [comment] 2017-09-01 13:08
So you agree that it should return maximumly k **unbroken** paths. That's great to keep simple. To be consistent, if there is no path at all, then it should return 0 path, right?

**Comment by ptpt** [comment] 2017-09-01 13:11
We have discussed this issue above. My suggestion was:

> Another possible solution is that: we add a new method OfflineMatchTopK, while we keep the OfflineMatch unchanged. The new method only returns at most k unbroken matches.

**Comment by kevinkreiser** [comment] 2017-09-01 13:33
my preference, although this is the least simple, is to always return at least one path (broken or not) and then not return further paths if they are broken.

**Comment by kevinkreiser** [comment] 2017-09-01 13:36
maybe we can make this approach simple by having the caller specify whether or not to return broken paths. so like in offline match we call it like `vs.SearchPath(time, k==0)` where `SearchPath(StateId::Time time, bool allowBrokenPaths)`

**Comment by kevinkreiser** [comment] 2017-09-01 13:37
this way only the 0th path will allow for a disconnected part but subsequent ones wont be returned, is that too messy @ptpt @dnesbitt61 ?

**Comment by ptpt** [comment] 2017-09-01 14:04
>  then it should return 0 path

I mean it should return empty paths. Sorry.

**Comment by kevinkreiser** [comment] 2017-09-01 14:23
i knew what i meant, i think returning 0 paths is not good. thats why i proposed above where we get at least 1 path broken or not.

**Comment by ptpt** [comment] 2017-09-01 19:05
If we offer both `OfflineMatch` and `OfflineMatchTopK`, it's easy to have the one you proposed:

```c++

std::vector<std::vector<Measurement>>
OfflineMatchAtLeast1Path(std::vector<Measurement>& measurements, int k)
{
    auto paths = OfflineMatchTopK(measurements, k);
    if (paths.empty())
        return {OfflineMatch(measurements)};
    else
        return paths;
}
```

**Comment by ptpt** [comment] 2017-09-18 14:24
I think https://github.com/valhalla/valhalla/issues/823#issuecomment-326581198 makes sense.

TODO:
1. [ ] return scores together with paths from `OfflineMatch`
2. [ ] if there is breakage, then the score should be -1.0

**Comment by ptpt** [comment] 2017-11-10 11:20
The TopK is implemented. Will open new issues for discussions about path scores. Closing.

Thanks all for discussion!

**Closed by ptpt** 2017-11-10 11:20 UTC
