### ISSUE TITLE
OSM ID > 10**15 exceeds maximum

### ISSUE THREAD

**Issue by nilsnolde** [valhalla/valhalla#1827] opened 2019-05-28 10:07 UTC
Hi,

we're importing TomTom data to Valhalla and make use of their node ID range to determine the OSM ID's for the OSM file to feed into Valhalla.

However, this is thrown:
```
2019/05/23 11:53:18.085630 [INFO] Parsing ways...
terminate called after throwing an instance of 'std::runtime_error'
  what():  OSMNode: exceeded maximum OSM node Id: 100000000390458
```

This is not even close to being out of range for 64-bit (signed or unsigned) integers.

Of course, OSM is a looong way from getting there with their ID range, and I realize supporting custom data dumps is not your top priority. I just want to test the waters, if you'd accept a PR where we accept the full 64-bit range? 

Tested our custom dump with GraphHopper and openrouteservice, there it works. But we do really like Valhalla and wouldn't want to ditch supporting it.

**Comment by kevinkreiser** [comment] 2019-05-28 12:54
When parse osm we pack the information about the node into a struct which we can easily serialize to file and memory map. Right now that structure is only 64bits wide, with 36 of those bits reserved for the node id. you can rearrage the OSMNode id structure to be 128bits wide and use the full 64bits for the node id if you like though this will double the size of the temporary storage we use for node processing (this is quite large already for the planet).

In terms of a PR perhaps this could be something that we enable with a compiler flag and `ifdef`'s. the changes *should* be quite small. something like:

```diff
diff --git a/valhalla/mjolnir/osmnode.h b/valhalla/mjolnir/osmnode.h
index bd72b4c7b..72b62f3c7 100644
--- a/valhalla/mjolnir/osmnode.h
+++ b/valhalla/mjolnir/osmnode.h
@@ -10,15 +10,23 @@
 namespace valhalla {
 namespace mjolnir {
 
+#ifdef LARGE_ID_SUPPORT
+constexpr uint64_t kMaxOSMNodeId = 18446744073709551615;
+#else
 constexpr uint64_t kMaxOSMNodeId = 68719476735;
+#endif
 constexpr uint32_t kMaxNodeNameIndex = 2097151;
 
 /**
  * OSM node information. Result of parsing an OSM node.
  */
 struct OSMNode {
-  // The osm id of the node
+// The osm id of the node
+#ifdef LARGE_ID_SUPPORT
+  uint64_t osmid_;
+#else
   uint64_t osmid_ : 36; // Allows up to 64B Ids
+#endif
   uint64_t access_ : 12;
   uint64_t type_ : 4;
   uint64_t intersection_ : 1;
```

And then some relevant changes in `CMakeLists.txt` to make sure the flag gets through and is defaulted to not being defined.

**Comment by nilsnolde** [comment] 2019-05-28 13:15
Thanks @kevinkreiser for the almost PR:) Yep, perfect, flag makes sense!

We never actually built the full planet. Just out of curiosity, how big is the temp storage approx with 64 bit?

**Comment by kevinkreiser** [comment] 2019-05-28 13:49
i think its somewhere in the low 10s of GB but i havent checked it in a while. you'll see intermediate files with the `.bin` extension when you are making the data, just throw a `du -h` at them to be sure!

**Comment by MichaelsJP** [comment] 2019-06-07 15:30
Hi and thank you @kevinkreiser a lot for the idea of the implementation :+1: 

I'm currently introducing the code. The implementation of your code and the cmake flag are working fine, it builds and all tests run through. But when I try to build tiles with bigger OSMIds it gets stuck at the serialization part at: `valhalla/mjolnir/idtable.h`. The code is constantly running into `bad_aloc` errors with an error looking like this:
```Max osmid exceeded bitset, resizing to fit id: 100000000390458
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc`
```
As far as I understood it, the current serialization/Indexing works by dividing the actual OSMId by 64 and using the resulting number as the Index location to store the OSMId. 

```if (id > maxosmid_) {
      LOG_WARN("Max osmid exceeded bitset, resizing to fit id: " + std::to_string(id));
      bitmarkers_.resize(std::ceil(idx * 1.01 + 1), 0);
      maxosmid_ = bitmarkers_.size() * 64 - 1;
 ```

As said, with smaller Ids from the tests etc. that works, but not with the Ids e.g. `100000000390458`. The default `kMaxOSMNodeId` is setting the `maxosmid` so small, that the storage has to resize immediately. Although that is intended,  I guess that using the bigger OSMIds for indexing by just dividing with 64, immediately exceeds the available size of the ` std::vector<uint64_t> bitmarkers_` index vector.

Do you have any idea how to solve this, without the need to massively increase the size of the vector and stay compliant with the smaller Ids?

**Comment by kevinkreiser** [comment] 2019-06-07 23:46
@MichaelsJP yeah.... Darn it... So that is an in memory bit map... To support an id that large you'd need like 12.5 terrabytes of ram..

The only way to fix this would be to use a completely different way of handling this. The problem here is that no matter what your ID set is way sparse compared to your largest id. we could, instead of using this bitset uset a hashmap, but that is going to take up 64 times the ram which might be reasonable but I cant remember off the top of my head how large this bitset gets. it might get pretty large already so its probably not a good idea to use a simple hashmap.

the best thing i think we could do is redesign this completely. as we encounter ways, we give them a sequential id starting at 0. and we set aside a sequence file, with the actual id stored in there. when we need to refer to the wayid (relations for example) we can look up the real way id with a two stage lookup. as soon as we are done needing to look up wayids we go back over all the ways and reassign their original id to them. i haven't looked at the code in a while so im not sure what gotchas are in there for this idea but on the surface it seems doable although much more involved.

many apologies for not realizing that up front!

**Comment by dnesbitt61** [comment] 2019-06-08 05:08
I agree with Kevin. A secondary lookup array sounds best, with a modification to graphbuilder to lookup the ID from the array when storing it in the EdgeInfo record.

**Comment by MichaelsJP** [comment] 2019-08-09 14:11
Hi @kevinkreiser  @dnesbitt61 , I finally found the time to get back on this issue. Thank you a lot for your suggestions. Setting up a sequence file and assigning the ways a new sequential id is definitely a straight forward idea.
Even though I would like to discuss two aspects of that:
1. Until we don't know if the first id we parse is the smallest id in the set, we can't set it to 0 for sure. The next id could be smaller and that would invalidate the new index.
2. Considered we have a sequence: To get the information if a node is already present in the sequence (e.g. for finding intersections), we need to iterate over that sequence/list/vector whatever, a lot. That would generate a huge overhead.

At moment the lookup to find e.g. intersections, just looks in the idTabe at the index that happens to be the same as the id that should be looked up. Very nice, fast and efficient! Downside is, as we discovered, if ids get too large, it will span the idTable from 0 - e.g. 100000000390458 and try to allocate (100000000390458·8)/1e+12 = +800 TB of RAM. Too much indeed ;).

My idea is to make a minimally invasive change. Instead of having to iterate over a large sequence structure many times, we just implement another iteration over the way nodes of the data set(s) inside `pbfgraphparser.cc`, before the usual parsers start their work:
1. With the first run we find the smallest and largest possible wayID in the file(s). Given the assumptions, that the ids have a logical structure/order behind them (the range can fit in a normal RAM; really large and small integers don't appear together) we can now create a new index for the idTable vector by subtracting the to be processed id with the smallest possible id. A data set that has an id range e.g. from 4000 to 40000 and one large id at 100000000390458, would be weird and I wouldn't consider that structured/ordered, so not normal ;).
2. The second and following iterations over all nodes will be the same as before, with small changes on how to set and get ids. To set an id it could work as followed: If we know the smallest id is 100000000000000 and the to be processed id is 100000000390458 we get the new index with (100000000390458 -  100000000000000) - 1 = 390457. In the opposite way, to see if an id is already set, we can just modify the old get() function a bit. So ids that should be looked up are just converted by the dynamic index and poof, found (so far the idea...). Two operations instead of a whole iteration with an increasing number of access operations.

If I'm right, this solution would solve the problem of the large id support without the need to rewrite that much code and/or tests.
It might even optimize the amount of RAM needed in general, and we could display the user beforehand on how much is needed to parse all ids and possibly do something with it instead of let the allocation crash silently.
One drawback is definitely that it will take a bit longer. I would try to test that with larger data sets, to see how much longer it takes. It could be an idea to increase the speed of that largest/smallest id check with multiple threads.
What it doesn't solve is the general storage problem of having too many or too diverse id sets.
But those problems have already been there before and are limited by the hardware in use.

Please let me know what you think about that :)

**Comment by dnesbitt61** [comment] 2019-08-12 12:34
If the IDs in your data set are such that the range is not huge (e.g., not some very small and some very large) then this could work. I would make this an optional step since parsing nodes for a large dataset can take a long time. I would not want to add this time to every data import for OSM datasets that do not need this additional step.

**Comment by kevinkreiser** [comment] 2019-08-12 17:53
@kevinkreiser I would add that, a valid osm data set has the objects in order of their ID. I fact there are other places in the code that rely on this and if you provide an osm extract that doesnt have the ids in increasng order `valhalla_build_tiles` will throw and log and exception saying as much and stopping the program.

**Comment by MichaelsJP** [comment] 2019-08-19 12:00
@kevinkreiser  Yeah, thanks for the hint. Very useful! Order is everything ;)!
@dnesbitt61  I see your point. I'm not going to implement that idea.
Instead, I now went with your previous idea of doing it with the extra ID files. I referenced the commit.
Even not polished, it works quite fine already. The way I do it now:

1. I iterate over all nodes and all way nodes in the beginning and store them in individual files (id_assignment_callback). Nodes get an increasing new ID, that starts at a specific base node (atm 1001).
--> The reason I iterate over nodes and way nodes is, once doing the ways later, it would be very time-consuming to find the new node from the node ids file because the way nodes don't come in sorted.
2. Once done with that I sort the way nodes ascending and iterate over them to assign the appropriate new ID from the original node IDs by looking up the IDs in the file.
3. I sort the way nodes back to original order, to be able to find them faster once the ways and way nodes get processed.
4. While processing the ways (way_callback), I iterate over the way nodes and find their counter part in the way nodes file and with that the new ID, because they have the same order (gotten from the first iteration at 1.).
5. While processing the nodes (node_callback), I look up the original ID at the beginning and the corresponding new osmid, which is used in the rest of the callback. When it comes to the updating of the way nodes I reassign the old/original node IDs, before it gets written to the way nodes file.

--> Issue with `4.`: There is still the unresolved question to whether assign new IDs to ways or change the way IDs variable to uint64 in general.
- If  assigning new IDs to ways, there is no possibility of assigning the original large way IDs back at the moment, as the way ID variable is uint32 in general. I also tried building without reassigning the IDs back to the original ones but the results differ a lot from the original one from master. I couldn't figure out why. My guess is, that the original file is accessed again somewhere at a later point.
- I went for the uint64 solution and changed the way ID variable in general to uint64. That works fine so far and all the tests pass.
- While the uint64 node IDs can be switched on and off with the LARGE_ID_SUPPORT cmakelist switch, the uint64 for the way nodes are not. There is too much depending on it, in my opinion to make everything optional.

What are your thoughts regarding the uint64 way node id?
Should I make everything optional regarding my change with the cmake switch, even the large way IDs?

**Comment by sheerun** [comment] 2019-12-30 10:26
I also get "Max osmid exceeded bitset, resizing to fit id: 6813595887" even for example in the readme (switzerland). Maybe it's good idea to increase default size?

**Comment by nilsnolde** [comment] 2019-12-30 11:23
That's not an issue @sheerun I think. The vector is constantly resizing whenever it encounters gradually higher OSM ID while moving through the PBF.

**Comment by kevinkreiser** [comment] 2019-12-30 17:18
@sheerun, @nilsnolde is correect. though, i do think we recently did as you said an increased the default (pretty sure it was @dnesbitt61 who took care of it).

**Comment by dnesbitt61** [comment] 2019-12-30 17:58
Yea, I increased it but looks like it already is dated. OSM is increasing at such rapid rate these days.

**Comment by kevinkreiser** [comment] 2020-06-09 23:27
after long wait, i believe we have some solutions to this problem:

#2410 #2415

**Comment by nilsnolde** [comment] 2020-06-10 05:38
Ui @kevinkreiser that’s awesome! I saw the way ID PR but figured the fairly easy approach you took there wouldn’t work here. Sooo happy to see this! Went to great lengths to come up with synthetic node IDs as the path of least resistance. Can ditch that crap now woohoo:)

**Comment by kevinkreiser** [comment] 2020-06-12 14:11
@nilsnolde there is still one remaining issue with the `64bit` branch. it seems we are missing one 32->64bit transformation in the restrictions processing. we've reproduced this by taking an extract and renumbering the ids to a higher range: `osmium renumber -s 4294967296 -o pa_renumbered.pbf pennsylvania-latest.osm.pbf`

once we get that straightened out i think this stuff is ready to ship. @gknisely is looking into it

**Comment by nilsnolde** [comment] 2020-06-12 15:10
Thanks for the heads-up @kevinkreiser ! At least we got the branch to build Switzerland OSM PBF already, but that wouldn't trigger any issue anyways I guess. Needs some hours to patch the converter software, so I'm fine if this can wait a few more days:)

**Closed** 2020-06-30 01:34 UTC

**Comment by nilsnolde** [comment] 2020-06-30 06:44
A few hours too late, but we can confirm that, with this fix, TomTom IDs (around 45ish bits) can be conveniently used as-is for OSM IDs :fireworks: Thanks for the great effort!

**Comment by nilsnolde** [comment] 2020-06-30 08:08
Also: the ID range is huge actually, from 1000 to 2^50. Still no memory issues processing 2.164.859 ways.
